### ISSUE TITLE
compiler crash when macros accessing global let variable

### ISSUE THREAD

**Issue by jangko** [nim-lang/Nim#11903]
not sure this is a regression or not, but it works with nim 0.19.xx

### Example
```nim
import sets

let BUILTIN_NAMES = toSet(["int8", "int16", "int32", "int64"])

macro test*(): untyped =
  echo "int64" notin BUILTIN_NAMES

test()
```

### Current Output
```
F:\projects\bug\quick.nim(3, 21) Warning: Deprecated since v0.20, use 'toHashSet'; toSet is deprecated [Deprecated]
fatal.nim(39)            sysFatal
Error: unhandled exception: vm.nim(707, 16) `nfIsRef in regs[ra].node.flags`  [AssertionError]
```

### Expected Output
```
false
```

### Possible Solution
* if the `let` changed to `const`, it works.
* annotate the `let` with `{.compileTime.}` pragma aslo works

### Additional Information

* if both let and echo statement put into static block, it works.

```
$ nim -v
Nim Compiler Version 0.20.99 [Windows: amd64]
Compiled at 2019-08-05
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: 61c66abbfea43752acb73d5c451fef5fce8e0d35
active boot switches: -d:release
```

**Comment by krux02** [comment]
I could not reproduce the problem. On my computer I get the output ``false``. But this is indeed a bug. This should be a compilation error. The macro should not be able to access variables that are neither ``compileTime`` nor ``const``.
