### ISSUE TITLE
error: 'T5_' undeclared (first use in this function)   (void)(T5_);

### ISSUE THREAD

**Issue by retsyo** [nim-lang/Nim#10842]
I am using latest cloned [wNim/winim](https://github.com/khchen/wNim), and latest cloned-and-built nim on win7 64 bits

I compile the kinds of examples in [wNim/winim](https://github.com/khchen/wNim) via `nim c -r xx.nim` or `nim c --threads:on -r xx.nim`. Several examples can't be compiled and show a similar error problem. I have [reported](https://github.com/khchen/wNim/issues/14) the problem. However it is seems that the problem roots in nim

demo.nim
```
CC: wnim_demo
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\demo_d\wnim_wnim.c.o C:\Users\USER\nimcache\demo_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\demo_d\wnim_wnim.c: In function 'drawPolygon_uj9bsThPSyVmHk8BPYRcrRg':
C:\Users\USER\nimcache\demo_d\wnim_wnim.c:40082:9: error: 'T5_' undeclared (first use in this function)
  (void)(T5_);
         ^~~
C:\Users\USER\nimcache\demo_d\wnim_wnim.c:40082:9: note: each undeclared identifier is reported only once for each function it appears in
```

dragdrop.nim
```
CC: wnim_wnim
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\dragdrop_d\wnim_wnim.c.o C:\Users\USER\nimcache\dragdrop_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\dragdrop_d\wnim_wnim.c: In function 'init_gx6K5jmJ70ZIoCilC9a9cEHA':
C:\Users\USER\nimcache\dragdrop_d\wnim_wnim.c:36148:10: error: 'T22_' undeclared (first use in this function)
   (void)(T22_);
          ^~~~
C:\Users\USER\nimcache\dragdrop_d\wnim_wnim.c:36148:10: note: each undeclared identifier is reported only once for each function it appears in
```

pickicondialog.nim
```
Hint: gdiplus [Processing]
pickicondialog.nim(189, 7) Hint: 'statusbar' is declared but not used [XDeclaredButNotUsed]
CC: wnim_pickicondialog
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\pickicondialog_d\wnim_pickicondialog.c.o C:\Users\USER\nimcache\pickicondialog_d\wnim_pickicondialog.c' failed with exit code: 1

C:\Users\USER\nimcache\pickicondialog_d\wnim_pickicondialog.c: In function 'showIcons_Pdzn9cJ5kCaQTOWP62ZMbJg':
C:\Users\USER\nimcache\pickicondialog_d\wnim_pickicondialog.c:4310:12: error: 'T31_' undeclared (first use in this function)
     (void)(T31_);
            ^~~~
C:\Users\USER\nimcache\pickicondialog_d\wnim_pickicondialog.c:4310:12: note: each undeclared identifier is reported only once for each function it appears in
```

reversi.nim
```
CC: wnim_reversi
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\reversi_d\wnim_wnim.c.o C:\Users\USER\nimcache\reversi_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\reversi_d\wnim_wnim.c: In function 'drawBitmap_xT161lcfQcK5qZmfT9aATXA':
C:\Users\USER\nimcache\reversi_d\wnim_wnim.c:33398:9: error: 'T11_' undeclared (first use in this function)
  (void)(T11_);
         ^~~~
C:\Users\USER\nimcache\reversi_d\wnim_wnim.c:33398:9: note: each undeclared identifier is reported only once for each function it appears in
```

scribble.nim
```
CC: wnim_scribble
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\scribble_d\wnim_wnim.c.o C:\Users\USER\nimcache\scribble_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\scribble_d\wnim_wnim.c: In function 'drawBitmap_xT161lcfQcK5qZmfT9aATXA':
C:\Users\USER\nimcache\scribble_d\wnim_wnim.c:35449:9: error: 'T11_' undeclared (first use in this function)
  (void)(T11_);
         ^~~~
C:\Users\USER\nimcache\scribble_d\wnim_wnim.c:35449:9: note: each undeclared identifier is reported only once for each function it appears in
```

tictactoe.nim
```
CC: wnim_tictactoe
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples -o C:\Users\USER\nimcache\tictactoe_d\wnim_wnim.c.o C:\Users\USER\nimcache\tictactoe_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\tictactoe_d\wnim_wnim.c: In function 'drawBitmap_xT161lcfQcK5qZmfT9aATXA':
C:\Users\USER\nimcache\tictactoe_d\wnim_wnim.c:33261:9: error: 'T11_' undeclared (first use in this function)
  (void)(T11_);
         ^~~~
C:\Users\USER\nimcache\tictactoe_d\wnim_wnim.c:33261:9: note: each undeclared identifier is reported only once for each function it appears in
```

autolayout\demo.nim
```
CC: wnim_demo
Error: execution of an external compiler program 'gcc.exe -c  -w -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN  -IE:\msys64\home\USER\_nim\nim\lib -IR:\khchen-wNim\examples\autolayout -o C:\Users\USER\nimcache\demo_d\wnim_wnim.c.o C:\Users\USER\nimcache\demo_d\wnim_wnim.c' failed with exit code: 1

C:\Users\USER\nimcache\demo_d\wnim_wnim.c: In function 'drawPolygon_uj9bsThPSyVmHk8BPYRcrRg':
C:\Users\USER\nimcache\demo_d\wnim_wnim.c:40082:9: error: 'T5_' undeclared (first use in this function)
  (void)(T5_);
         ^~~
C:\Users\USER\nimcache\demo_d\wnim_wnim.c:40082:9: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by mratsim** [comment]
According to the linked issue, this works on 0.19.0.

**Comment by krux02** [comment]
minimized example to reproduce the problem
```nim
proc myDiscardable(): int {.discardable.} =
  discard

proc main() =
  defer:
    echo "something defered"
  myDiscardable()

main()
```

**Comment by krux02** [comment]
git bisect did tell me it was this PR: https://github.com/nim-lang/Nim/pull/10322

**Comment by retsyo** [comment]
so, is there any solution?

**Comment by Araq** [comment]
> so, is there any solution?

Not yet, but there's a showstopper PR that will fix this problem.

**Comment by Araq** [comment]
This should work now.
