### ISSUE TITLE
`__stderrp` and friends not defined on OpenBSD

### ISSUE THREAD

**Issue by euantorano** [nim-lang/Nim#13733]
When trying to compile Nim on OpenBSD, you hit errors like the following:

```
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:1656:11: error: use of undeclared identifier '__stderrp'
        rawWrite(__stderrp, "out of memory\012");
                 ^
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:5751:11: error: use of undeclared identifier '__stderrp'
        rawWrite(__stderrp, msg);
                 ^
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:5945:12: error: use of undeclared identifier '__stderrp'
                rawWrite(__stderrp, "[GC] cannot register thread local variable; too many thread loc"
                         ^
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:6099:12: error: use of undeclared identifier '__stderrp'
                rawWrite(__stderrp, "[GC] cannot register global variable; too many global variables");
                         ^
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:7149:11: error: use of undeclared identifier '__stderrp'
        rawWrite(__stderrp, nimToCStringConv(errormsg));
                 ^
/home/euant/.cache/nim/koch_d/stdlib_system.nim.c:7151:11: error: use of undeclared identifier '__stderrp'
        rawWrite(__stderrp, "\012");
                 ^
6 errors generated.
Error: execution of an external program failed: 'clang -c  -w  -I/home/euant/Nim/lib -I/home/euant/Nim -o /home/euant/.cache/nim/koch_d/stdlib_system.nim.c.o /home/euant/.cache/nim/koch_d/stdlib_system.nim.c'
```

This is caused by commit e70294d.

**Comment by euantorano** [comment]
This seems to also affect NetBSD too, based upon a quick look at their source.
