### PR TITLE
[closes #12682]add testcase for #12682

### LINKED ISSUE #12682: regression(1.0): codegen error with `locals`
regression(1.0): codegen error with `locals`

### Example
reduced from a more complex case:
```nim
  template foo*(): untyped =
    var c1 = locals()
    1

  proc testAll()=
    doAssert foo() == 1
    let c2=locals()
  testAll()
```

nim c -r main.nim

### Current Output
```
/nimcache/@mt0787.nim.c:102:14: error: use of undeclared identifier 'c1X60gensym393408_'
        c2.Field0 = c1X60gensym393408_;
```

### Expected Output
no error

### Additional Information
* It was working in version 0.19.0
* bug is in recent devel f22d3c75aa68833ae1b01d747d0c71074ccef310; also in 1.0.0

### PR DESCRIPTION
**Pull request by ringabout**

### CODE REVIEW

File: tests/ccgbugs/t12682.nim [hunk 1]
```diff
@@ -0,0 +1,13 @@
+discard """
+  action: compile
+"""
+
```
Comment (timotheecour) [inline tests/ccgbugs/t12682.nim]: merge into tests/misc/tlocals.nim with a `block: # bug #12682`

File: tests/ccgbugs/t12682.nim [hunk 2]
```diff
@@ -0,0 +1,13 @@
+discard """
```
Comment (timotheecour) [inline tests/ccgbugs/t12682.nim]: you should get rid of those 3 lines so it compiles + runs
