### ISSUE TITLE
Regression from 2.2.10 to `version-2-2`/`devel` with `proc r(e: ref Exception) {.raises: [IOError].} = raise (ref IOError)(e)`

### ISSUE THREAD

**Issue by tersec** [nim-lang/Nim#25885]
### Nim Version

Pre-regression:
```
Nim Compiler Version 2.2.10 [Linux: amd64]
Compiled at 2026-06-09
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: bfeb3146d1638b39f69007a4ae5a23e23ae4e5ef
active boot switches: -d:release
```

Post-regression:
```
Nim Compiler Version 2.2.11 [Linux: amd64]
Compiled at 2026-06-09
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: 2c6191aa4da97acdc6dc40e9a959e1ec75fae4d4
active boot switches: -d:release
```

```
Nim Compiler Version 2.3.1 [Linux: amd64]
Compiled at 2026-06-09
Copyright (c) 2006-2026 by Andreas Rumpf

git hash: e942da94b5b52fa7e09b133d52125037ba69c7b7
active boot switches: -d:release
```

### Description

```nim
static: doAssert IOError is Exception
proc r(e: ref Exception) {.raises: [IOError].} = raise (ref IOError)(e)
```

### Current Output

```text
/tmp/j.nim(2, 70) Error: e can raise an unlisted exception: ref Exception
```

### Expected Output

```text
No compilation error
```

**Comment by narimiran** [comment]
`git bisect` shows https://github.com/nim-lang/Nim/pull/25845 as the first problematic commit, cc @ringabout

**Comment by Araq** [comment]
Yeah the `skipConvCastAndClosure(e)` is wrong here, should have caught that, mea culpa.

**Comment by ringabout** [comment]
My bad, I will revert my PR
