### ISSUE TITLE
Incorrectly generated code for generic DoublyLinkedList item

### ISSUE THREAD

**Issue by tommo** [nim-lang/Nim#18838]
With the current devel nim, compilation fails if DoublyLInkedNode is used with a 'recursive' generic parameter.

Minimal example:
```nim
import lists

type
  Box = object
  Item[T] = ref object
    link:DoublyLinkedNode[ Item[T] ]

  ItemSimple = ref object
    link:DoublyLinkedNode[ ItemSimple ]

let link = newDoublyLinkedNode( Item[Box]() )
```

```
### Current Output
/Volumes/prj/test/genbug2.nim(11, 5) Hint: 'link' is declared but not used [XDeclaredButNotUsed]
CC: genbug2.nim
/Users/tommo/.choosenim/toolchains/nim-#devel/lib/pure/collections/lists.nim:158:111: error: assigning to 'tyObject_Box__9bGh9cASM2hnWCK9buLK60G7A' (aka 'struct tyObject_Box__9bGh9cASM2hnWCK9buLK60G7A') from incompatible type 'tyObject_ItemcolonObjectType___mwZGZYZQx3zx3zd4LT4c3g *' (aka 'struct tyObject_ItemcolonObjectType___mwZGZYZQx3zx3zd4LT4c3g *')
        nimln_(158, "/Users/tommo/.choosenim/toolchains/nim-#devel/lib/pure/collections/lists.nim");    (*result).value = value;        }BeforeRet_: ;
                                                                                                                        ^ ~~~~~
1 error generated.
Error: execution of an external compiler program 'clang -c -w -ferror-limit=3 -pthread -g -Os   -I'/Users/tommo/.choosenim/toolchains/nim-#devel/lib' -I/Volumes/prj/test -o /Volumes/prj/test/_build/.nimcache/@mgenbug2.nim.c.o /Volumes/prj/test/_build/.nimcache/@mgenbug2.nim.c' failed with exit code: 1

```
This fails with both C and CPP backends.
Using  latest devel:
```
Nim Compiler Version 1.5.1 [MacOSX: amd64]
Compiled at 2021-09-12
Copyright (c) 2006-2021 by Andreas Rumpf

git hash: 5d1608c9764416e74b36f6a772f16a66d58ddc28
active boot switches: -d:release
```

**Comment by ghost** [comment]
`git bisect` shows:
```
7ae52d779184cd8a16b760e384777a75ed54464b is the first bad commit
commit 7ae52d779184cd8a16b760e384777a75ed54464b
Author: Jason Beetham <beefers331@gmail.com>
Date:   Mon Sep 6 01:43:26 2021 -0600

    Fix recursive generic typed defs (#18809)

 compiler/semtypinst.nim               |  2 +-
 tests/generics/trecursivegenerics.nim | 12 ++++++++++++
 2 files changed, 13 insertions(+), 1 deletion(-)
 create mode 100644 tests/generics/trecursivegenerics.nim
bisect run success
```

So 7ae52d779184cd8a16b760e384777a75ed54464b is the first failing commit (https://github.com/nim-lang/Nim/pull/18809). I'm not sure if it's the root cause of this issue or not, but nonetheless, ping @beef331 :)

**Comment by ghost** [comment]
A bit simplified:
```nim
type
  # if you merge DoublyLinkedNodeObj and DoublyLinkedNode (so that it's ref object)
  # the compilation error doesn't occur
  DoublyLinkedNodeObj[T] = object
    value: T

  DoublyLinkedNode[T] = ref DoublyLinkedNodeObj[T]

  Item[T] = ref object
    link: DoublyLinkedNode[Item[T]]

  Box = object

proc newDoublyLinkedNode[T](value: T): DoublyLinkedNode[T] =
  new(result)
  result.value = value # this line fails to compile in C/C++ backends

let link = newDoublyLinkedNode(Item[Box]())
```

**Comment by beef331** [comment]
Can confirm it was that commit, but not a clue why the objects arent the same, seems what I did has a sideffect that the `.value` and `value` are not the same objects anymore(in C land due to the typecache). Oddly the colon expr still works:
```nim
type
  # if you merge DoublyLinkedNodeObj and DoublyLinkedNode (so that it's ref object)
  # the compilation error doesn't occur
  DoublyLinkedNodeObj[T] = object
    value: T

  DoublyLinkedNode[T] = ref DoublyLinkedNodeObj[T]

  Item[T] = ref object
    link: DoublyLinkedNode[Item[T]]

  Box = object
    a: int

proc newDoublyLinkedNode[T](value: T): DoublyLinkedNode[T] = DoublyLinkedNode[T](value: value)

let link = newDoublyLinkedNode(Item[Box]())
```
