### ISSUE TITLE
C Error "redeclaration of X with no linkage"

### ISSUE THREAD

**Issue by Wh1teDuke** [nim-lang/Nim#11483]
**Test:**
```nim
proc main =
  template first(body) =
    template second: var int =
      var o: int
      var i  = addr(o)
      i[]

    body
      
  first:
    second = 5
    second = 6
      
main()
```
**Error:**
```nim
/[...]/test2.nim.c: In function ‘main_XWgRB52wRcomZYFcqNiyzQ’:
/[...]/test2.nim.c:79:5: error: redeclaration of ‘o’ with no linkage
  NI o;
     ^
/[...]/test2.nim.c:77:5: note: previous declaration of ‘o’ was here
  NI o;
     ^
/[...]/test2.nim.c:80:6: error: redeclaration of ‘i’ with no linkage
  NI* i;
      ^
/[...]/test2.nim.c:78:6: note: previous declaration of ‘i’ was here
  NI* i;
      ^
```
Regression (0.19.6 compiles it fine).
***
```nim
>nim -v
Nim Compiler Version 0.20.99 [Linux: i386]
Compiled at 2019-06-12
Copyright (c) 2006-2019 by Andreas Rumpf

git hash: c07973e313cb701a076bffb890c0777a555ffa16
active boot switches:
```

**Comment by narimiran** [comment]
According to `git bisect`, this regression was caused by https://github.com/nim-lang/Nim/commit/2475d92c36e26e44372175c2cf4c21fbab084619
