### ISSUE TITLE
marshal.load() regression?

### ISSUE THREAD

**Issue by trustable-code** [nim-lang/Nim#7854]
Example program:
```nim
import marshal
import streams
type MyType = ref object
  field*: string
var list: seq[MyType]
let stream = newFileStream("input_file.json", fmRead)
marshal.load(stream, list)
```
Gives compilation error:
```Error: for a 'var' type a variable needs to be passed; but 'seq[MyType](list)' is immutable```

Nim Compiler Version 0.18.1 [Linux: amd64]
Compiled at 2018-05-20
git hash: dedf0f3e19332c02562689b168cc4ac45b812174
active boot switches: -d:release

Works with Nim 0.18.0.

**Comment by sinkingsugar** [comment]
I'm having the same issue after pulling devel.

**Comment by Vindaar** [comment]
Since I was curious what the issue is, I tried to remove everything that's not needed from the example in the OP. It seems to come down to a generic `var` argument at the second argument + an inherited type.
To summarize:
```nim
type
  Stream* = ref StreamObj
  StreamObj* = object of RootObj

  InhStream* = ref InhStreamObj
  InhStreamObj* = object of Stream
    f: string

proc newInhStream*(f: string): InhStream =
  new(result)
  result.f = f

var val: int
let str = newInhStream("input_file.json")

block:
  # works:
  proc load[T](data: var T, s: Stream) =
    discard
  load(val, str)

block:
  # works
  proc load[T](s: Stream, data: T) =
    discard
  load(str, val)

block:
  # broken
  proc load[T](s: Stream, data: var T) =
    discard
  load(str, val)
```
