### ISSUE TITLE
Invalid c codegen with orc/arc enabled on gcc/mingw 

### ISSUE THREAD

**Issue by ovenpasta** [nim-lang/Nim#24235]
### Description

When using the c backend thec complation fails. I am using gcc/mingw (5.5.0) and orc / arc enabled.
The issue is not there for gcc 14/linux 

### Nim Version

2.0.8 and 2.2.0 probably earlier versions also

### Current Output

```text
cache/@m..@s..@s..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.0@slib@ssystem.nim.c: In function 'osDeallocPages__system_u5797':
cache/@m..@s..@s..@s..@s..@s..@s..@s.choosenim@stoolchains@snim-2.2.0@slib@ssystem.nim.c:1773:7: error: void value not ignored as it ought to be                        
   T6_ = printf("virtualFree failing!");
```

### Known Workarounds

use --mm:refc

**Comment by metagn** [comment]
Bug with old GCC version, no? `printf` is supposed to return an int. Seems to work fine on gcc 6.3 or 7.4.

**Comment by ovenpasta** [comment]
Sorry you are right, must be something on my system, printf must return int in any case...
I close this.
