### PR TITLE
combine PR#16009 and PR#16012

### LINKED ISSUE #15623: gcc error "invalid use of void expression" from (mis)use of nil
### Example
```nim
when defined(direct):
  echo cast[ptr int](nil)[]

when defined(indirect):
  var x: ref int = nil
  echo cast[ptr int](x)[]
```

### Current Output -d:indirect
```
Traceback (most recent call last)
/home/jfondren/nim/learn/error1.nim(6) error1
SIGSEGV: Illegal storage access. (Attempt to read from nil?)
```

### Current Output -d:direct
```
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c: In function ‘NimMainModule’:
/home/jfondren/.cache/nim/error1_d/@merror1.nim.c:152:24: error: invalid use of void expression
  152 |  T1_[0] = nimIntToStr((*NIM_NIL));
      |                       ~^~~~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I/home/jfondren/.choosenim/toolchains/nim-1.4.0/lib -I/home/jfondren/nim/learn -o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c.o /home/jfondren/.cache/nim/error1_d/@merror1.nim.c' failed with exit code: 1
```

### Additional Information
This isn't a blocker to anything. This is my riffing off someone's `nil[]` joke from IRC.
```
$ nim -v
Nim Compiler Version 1.4.0 [Linux: amd64]
Compiled at 2020-10-16
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: bdcd87afca238a0a7b2c70971827cf9172817b12
active boot switches: -d:release
```

### PR DESCRIPTION
**Pull request by ringabout**
fix #15623

### CODE REVIEW

File: tests/ccgbugs/t15623.nim [hunk 1]
```diff
@@ -0,0 +1,11 @@
+discard """
+  action: "compile"
+"""
+
+# bug #15623
+block:
+  echo cast[ptr int](nil)[]
```
Comment (timotheecour) [inline tests/ccgbugs/t15623.nim]: * you can remove
```
discard """
  action: "compile"
"""
```
(hence make the test megatest-joinable, and simpler to use also) as follows:

```nim
block:
  if false:
   let a = cast[ptr int](nil)[]
```

* ditto elsewhere

**Comment by ringabout** [comment]
Now VM and constexpr(so does before) support cast nil to NilableTypes:

```nim
block:
  static:
    echo cast[RootRef](nil).repr

block:
  static:
    echo cast[cstring](nil).repr
```
The CI failure before is caused by #16012 remove cast ref to nil supports for constexpr but tested this in #16009.

File: tests/ccgbugs/t15623.nim (hunk 1 above)
Comment (ringabout) [reply tests/ccgbugs/t15623.nim]: Done. Thanks!

File: tests/ccgbugs/t15623.nim [hunk 2]
```diff
@@ -0,0 +1,11 @@
...
+
+block:
```
Comment (timotheecour) [inline tests/ccgbugs/t15623.nim]: optional:
stronger test:
```nim
when true:
  import segfaults
  var x: ref int = nil
  doAssertRaises(NilAccessDefect):
    let s = cast[ptr int](x)[]
```
(EDIT: if you do, add `joinable:false` because `import segfaults` has global effects wrt signal handlers)

File: tests/ccgbugs/t15623_2.nim [hunk 3]
```diff
@@ -0,0 +1,13 @@
+discard """
+  output: '''0
```
Comment (timotheecour) [inline tests/ccgbugs/t15623_2.nim]: better / more readable style (the 1st char can be on a newline, with same semantics):
```nim
output: '''
0
0
'''
```

(but see next comment)

File: tests/ccgbugs/t15623_2.nim [hunk 4]
```diff
@@ -0,0 +1,13 @@
...
+0
+'''
+"""
+
+# bug #15623
+block:
+  echo cast[int](cast[ptr int](nil))
```
Comment (timotheecour) [inline tests/ccgbugs/t15623_2.nim]: https://nim-lang.github.io/Nim/contributing.html
> Use boolean conditions and doAssert for the testing by itself, don't rely on echo statements or similar

`doAssert cast[int](cast[ptr int](nil)) == 0`

* ditto elsewhere

File: tests/ccgbugs/t15623_2.nim (hunk 3 above)
Comment (ringabout) [inline tests/ccgbugs/t15623_2.nim]:
```suggestion
  output: '''
0
```

File: tests/ccgbugs/t15623_2.nim (hunk 4 above)
Comment (ringabout) [reply tests/ccgbugs/t15623_2.nim]: I will clean tests after seeing whether CI can pass.

File: tests/ccgbugs/t15623.nim [hunk 5]
```diff
@@ -0,0 +1,8 @@
...
+  if false:
+    discard cast[ptr int](nil)[]
```
Comment (timotheecour) [inline tests/ccgbugs/t15623.nim]: (i had edited my previous comment too late)
```nim
  discard cast[ptr int](nil)[]
=>
  let s = cast[ptr int](nil)[]
```

(`discard` already worked before PR)

Comment (ringabout) [reply tests/ccgbugs/t15623.nim]: I will revert this test now.

File: tests/ccgbugs/t15623_2.nim [hunk 6]
```diff
@@ -0,0 +1,7 @@
+# bug #15623
```
Comment (timotheecour) [inline tests/ccgbugs/t15623_2.nim]: * move both this and tests/ccgbugs/t15623.nim inside:
`tests/misc/tcast.nim` under a
```nim
block: # bug #15623
  ...
```

* `tests/vm/tcastnil.nim` could also be moved there

it makes it easier to consolidate tests (eg so that all tests run on all backends: c,cpp,js,vm thus increasing test coverage; see for eg tests/misc/taddr.nim)
for vm it's the classical:
```nim
template main=
  # everything moved inside here
  # if something doesn't work yet for a backend eg vm:
  when nimvm: discard # BUG doesn't yet work 
  else: someTest()
  # etc
    
static: main()
main()
```

File: lib/posix/posix_linux_amd64_consts.nim [hunk 7]
```diff
@@ -365,7 +365,7 @@ const SCHED_RR* = cint(2)
 const SCHED_OTHER* = cint(0)
 
 # <semaphore.h>
-const SEM_FAILED* = cast[pointer]((nil))
+const SEM_FAILED* = nil
```
Comment (timotheecour) [inline lib/posix/posix_linux_amd64_consts.nim]: `const SEM_FAILED* = pointer(nil)` ? although seems unrelated to PR

Comment (ringabout) [inline lib/posix/posix_linux_amd64_consts.nim]:
```suggestion
const SEM_FAILED* = cast[pointer]((nil))
```

Comment (ringabout) [reply lib/posix/posix_linux_amd64_consts.nim]: `const a = cast[pointer](nil)` and `const a = nil` are the same I guess.

File: tests/vm/tcastnil.nim [hunk 8]
```diff
@@ -0,0 +1,35 @@
...
+  static:
+    echo cast[ptr int](nil).repr
+
+block:
+  static:
+    echo cast[RootRef](nil).repr
+
+block:
+  static:
+    echo cast[cstring](nil).repr
```
Comment (timotheecour) [inline tests/vm/tcastnil.nim]: same comment as previously, doAssert is better; testament only checks that nimout (+friends) is a subset of the stdout output, so if someone later adds some test, it may succeed for the wrong reasons (yes, this happened before).
=>
```nim
doAssert cast[cstring](nil).repr == "nil"
```
(it also makes this testament joinable; i'm not unsure if that's the case with a nimout section)

**Review by timotheecour — APPROVED** [review]
LGTM (remaining nits could be done in either this PR or subsequent one)

File: tests/misc/tcast.nim [hunk 9]
```diff
@@ -29,3 +29,47 @@ reject: discard cast[enum](0)
...
+    static:
+      doAssert cast[ptr int](nil).repr == "nil"
+
+  block:
+    const str = cast[ptr int](nil)
+    static:
+      doAssert str.repr == "nil"
+
+  block:
+    static:
```
Comment (timotheecour) [inline tests/misc/tcast.nim:66]: optional nit: some of these blocks could be combined into 1 block, eg:
```nim
block:
  static:
    doAssert cast[ptr int](nil).repr == "nil"
    doAssert cast[RootRef](nil).repr == "nil"
```
