### ISSUE TITLE
Building DLL with --noMain produces an unexpected DllMain on devel branch

### ISSUE THREAD

**Issue by saffage** [nim-lang/Nim#22321]
### Description

If we try to compile the following code:

```nim
import std/winlean

proc NimMain() {.cdecl, importc.}

proc DllMain*(hModule: Handle; reasonForCall: DWORD; reserved: pointer): WINBOOL {.stdcall, exportc, dynlib.} =
  if reasonForCall == 1:
    NimMain()
  
  return 1
```

Using the following command:

```cmd
nim c --app:lib --noMain mymodule.nim 
```

We will get a compilation error reporting a type conflict between two **DllMain** definitions as if we had not provided **--noMain**.
If we try to compile the same code with the same command on a stable branch, there is no error and the DLL will compile.

### Nim Version

Nim Compiler Version 1.9.5 [Windows: amd64]
Compiled at 2023-07-22
Copyright (c) 2006-2023 by Andreas Rumpf   

git hash: https://github.com/nim-lang/Nim/commit/62869a5c68e4dd91e00ee77b039f0175482ef4fa
active boot switches: -d:release

### Current Output

```text
C:\Users\User\nimcache\mymodule_d\@mmymodule.nim.c:123:13: error: conflicting types for 'DllMain'; have 'BOOL(struct HINSTANCE__ *, DWORD,  void *)' {aka 'int(struct HINSTANCE__ *, long unsigned int,  void *)'}
  123 | BOOL WINAPI DllMain(HINSTANCE hinstDLL, DWORD fwdreason,
      |             ^~~~~~~
In file included from C:\Users\User\nimcache\mymodule_d\@mmymodule.nim.c:7:
C:\Users\User\nimcache\mymodule_d\@mmymodule.nim.c:69:30: note: previous definition of 'DllMai 
' with type 'NI32(NI,  NI32,  void *)' {aka 'int(long long int,  int,  void *)'}
   69 | N_LIB_EXPORT N_STDCALL(NI32, DllMain)(NI hModule_p0, NI32 reasonForCall_p1, void* reserved_p2) {      
      |                              ^~~~~~~
C:\Users\User\.choosenim\toolchains\nim-#devel\lib/nimbase.h:167:54: note: in definition of macro 'N_STDCALL'
  167 | #  define N_STDCALL(rettype, name) rettype __stdcall name
      |                                                      ^~~~
Error: execution of an external compiler program 'gcc.exe -c  -w -fmax-errors=3 -mno-ms-bitfields -DWIN32_LEAN_AND_MEAN   -IC:\Users\User\.choosenim\toolchains\nim-#devel\lib -IC:\nim-dllmain -o C:\Users\User\nimcache\mymodule_d\@mmymodule.nim.c.o C:\Users\User\nimcache\mymodule_d\@mmymodule.nim.c' failed with exit code: 1
```

### Expected Output

```text
Build DLL
```

### Additional Information

This started happening on the devel branch build dated **2023-05-27** and supposedly caused by the commit https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15

**Comment by metagn** [comment]
@ringabout In https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15, why does [`--app:lib` imply noMain](https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15#diff-d949f8c356fd2dc9ceedc6f3dbbd01e2c806269dd0a8ad6516facf589fa2c99aR802), but then this is [immediately ignored](https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15#diff-a7b99c432cd05c4b08fd12ee4216d90e362a3b900de6a9513792a6b1d7246d3eL1636-R1636) and the main function is generated anyway? Shouldn't the 2 diffs I linked be reverted?

**Comment by ringabout** [comment]
> In https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15, why does [--app:lib imply noMain](https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15#diff-d949f8c356fd2dc9ceedc6f3dbbd01e2c806269dd0a8ad6516facf589fa2c99aR802), but then this is [immediately ignored](https://github.com/nim-lang/Nim/commit/609bf3d7c8bf880dea70f6e8211976f3ec15#diff-a7b99c432cd05c4b08fd12ee4216d90e362a3b900de6a9513792a6b1d7246d3eL1636-R1636) and the main function is generated anyway? Shouldn't the 2 diffs I linked be reverted?

Make sense.
