### ISSUE TITLE
[ARC] C compiler error when using the result of a template in the subscript operator

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#20303]
### What happened?

This code shows a C compiler error during compilation when compiled with `--gc:arc`:

```nim
template minIndexByIt: untyped =
  var other = 3
  other

proc main() =
  var hlibs = @["hello", "world", "how", "are", "you"]
  let res = hlibs[minIndexByIt()]
  echo res

main()
```

Found in gintro's binding generator while trying to install it.
### Nim Version

Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-09-04
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 23e0160af283bb0bb573a86145e6c1c792780d49
active boot switches: -d:release

### Current Standard Output Logs

```shell
/home/dian/.cache/nim/tast_d/@mtast.nim.c:134:5: error: redefinition of 'otherX60gensym0_'
        NI otherX60gensym0_;
           ^
/home/dian/.cache/nim/tast_d/@mtast.nim.c:133:5: note: previous definition is here
        NI otherX60gensym0_;
```

### Additional Information

Works without ARC/ORC

**Comment by ringabout** [comment]
works in 1.4.8
expanded:

```nim
var
  hlibs
  res
try:
  hlibs = @["hello", "world", "how", "are", "you"]
  res = hlibs[
    var other`gensym0 = 3
    other`gensym0]
  wasMoved(hlibs[
    var other`gensym0 = 3
    other`gensym0])
  echo [res]
finally:
  `=destroy`(res)
  `=destroy_1`(hlibs)
```

Expressions with side effects are broken in this case:

```nim
proc minIndexByIt: int =
  echo 10
  var other = 3
  other

proc main() =
  var hlibs = @["hello", "world", "how", "are", "you"]
  let res = hlibs[minIndexByIt()]
  echo res

main()
```

prints `10` twice but shouldn't

**Comment by ringabout** [comment]
Imo, it is possible for bracketExpr has side effects. The Nim compiler should generate a temporary variable to store the index expression.

Probably something like below:

```nim
var
  hlibs
  res
try:
  hlibs = @["hello", "world", "how", "are", "you"]
  let bracketTmp =
    var other`gensym0 = 3
    other`gensym0
  res = hlibs[bracketTmp]
  wasMoved(hlibs[bracketTmp])
  echo [res]
finally:
  `=destroy`(res)
  `=destroy_1`(hlibs)
```

With regard to performance, the Nim compiler may choose to generate an inline expression if it is a simple expression without side effects.
