### ISSUE TITLE
"distinct uint64" type corruption on 32-bit, when using {.borrow.} operators

### ISSUE THREAD

**Issue by stefantalpalaru** [nim-lang/Nim#13902]
The problem only appears when borrowed operators for a "distinct uint64" type force a type inference.

### Example
```nim
type Slot = distinct uint64

var s = Slot(1)

proc `$`*(x: Slot): string {.borrow.}
proc `+=`*(x: var Slot, y: uint64) {.borrow.}

echo "s = ", s
s += 1
echo "s = ", s
```

Compiling and running a 32-bit binary on a 64-bit Linux system: `nim c -r --cpu:i386 --passC:"-m32" --passL:-m32 uint64.nim`

### Current Output
```
s = 1
s = 6223254620873949186
```

### Expected Output
```
s = 1
s = 2
```

### Additional Information

Found when porting nim-beacon-chain to Nim-1.2.0: https://github.com/status-im/nim-beacon-chain/pull/829

```
$ nim -v
Nim Compiler Version 1.2.0 [Linux: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release
```

**Comment by stefantalpalaru** [comment]
It seems to only apply to borrowed operators with var params. This one works:
```nim
proc `+`*(x: Slot, y: uint64): Slot {.borrow.}
```

**Comment by mratsim** [comment]
This used to work in 1.0.6 and appeared in 1.2.0

**Comment by stefantalpalaru** [comment]
Regression introduced by this commit: https://github.com/nim-lang/Nim/commit/19cab9fa51fdb9a244ca35e978e9daa8cc81a785

Paging @timotheecour.

What looks suspicious in there is that a new "frameMsgLen" field is added unconditionally to `struct TFrame_` in "nimbase.h" but then it's added conditionally to `TFrame` in "system.nim".

Adding `--stacktraceMsgs:on` to `nim`'s command line does not fix the problem, but commenting out that extra field in "nimbase.h" does.

I thought adding the missing struct field to this anonymous struct copy of `TFrame_` would help, but it doesn't: https://github.com/nim-lang/Nim/blob/19cab9fa51fdb9a244ca35e978e9daa8cc81a785/compiler/cgen.nim#L622

I'm out of ideas for what could cause a wrong length assumption for that struct.

**Comment by alaviss** [comment]
I don't think that's the problem. Your problem lies in the C code:

```c
	nimln_(9, "/tmp/test.nim");	if (nimAddInt(s__1PREurDxZ5w0Xbv7yMs9aWw, 1ULL, &TM__ipcYmBC9bj9a1BW35ABoB1Kw_3)) { raiseOverflow(); };	s__1PREurDxZ5w0Xbv7yMs9aWw = (NU64)(TM__ipcYmBC9bj9a1BW35ABoB1Kw_3);
```

This code is used to add integers, and on 32bit systems, they'll be treated as 32bit ints. That's where the corruption came from.

This regression was introduced and/or surfaced by @Araq's #13626.

**Comment by stefantalpalaru** [comment]
I used `git bisect` to find the first commit with the regression.

**Comment by timotheecour** [comment]
i will look into it in a bit, today

**Comment by alaviss** [comment]
Guess I catched another regression: distinct uints still have their bounds checked.

**Comment by timotheecour** [comment]
> I used git bisect to find the first commit with the regression.

I believe you've used git bisect incorrectly :-)
I ran git bisect and it found instead exactly the commit I was suspecting: a6682de0045468ae1d15afbd2fd5378960e15eb7 catchable defects (#13626)
(which, like all great PRs, can sometimes introduce regressions)

/cc @Araq 

(and also verified manually right before and right after this commit)

btw, maybe it's time to look more closely into the other comments that have been marked as resolved but IMO are still valid on that PR (even if some of these refer to pre-existing issues)

These concern bound checking codegen issues and potential double evaluation bugs/performance bugs, eg  https://github.com/nim-lang/Nim/pull/13626#discussion_r391627793 amongst others

**Comment by stefantalpalaru** [comment]
> I believe you've used git bisect incorrectly :-)

Doubt it. I started from https://github.com/nim-lang/Nim/commit/6e0c06f50e0450522b32a1bad23a3d2a4e36e9f9 mentioned by leorize as working, on IRC, then manually verified the result by checking out https://github.com/nim-lang/Nim/commit/8088633250872de8777c7078e636b2379780e107 which works and https://github.com/nim-lang/Nim/commit/19cab9fa51fdb9a244ca35e978e9daa8cc81a785 which fails.

It may be possible that the problem appeared and disappeared as the stack changed in unrelated places, but keep in mind that it's solved by removing "frameMsgLen" from `struct TFrame_`.

**Comment by timotheecour** [comment]
> It may be possible that the problem appeared and disappeared as the stack changed in unrelated places, but keep in mind that it's solved by removing "frameMsgLen" from struct TFrame_.

`--stacktrace:off` would exhibit the bug with  1.2.0 so I can't see how https://github.com/nim-lang/Nim/pull/13351 could relate. The root cause is #13626 which has buggy semantics for things like `mInc` (+=) for distinct unsigned, which could trigger in #13351 but not because of it. Note that it also triggers or not depending on random unrelated code modifications happening between #13626 <= here < #13351 so again, it should be unrelated to that.

I found the bug and am fixing it in https://github.com/nim-lang/Nim/pull/13907 (just a 1 line change, plus a test).

note that it also fixes a (related) cpp codegen compilation error

**Comment by Araq** [comment]
I have said it elsewhere, "git bisect" can have false positives and other ways for bug hunting are much more effective. Like, I dunno, trying to understand what's actually going on.

**Comment by timotheecour** [comment]
> I have said it elsewhere, "git bisect" can have false positives

It's about reducing the search space.
In large majority of cases there is a single good=>bad transition even if you have intermediate broken commits (eg because a PR was not squashed). When there are multiple (accidental) good=>bad transition, either the `git bisect run` test can be made more strict, or you can still automate the task of finding the first transition, even if, strictly speaking, that's O(N) worst case complexity in this case (but that would be rare).

it's trivial to write a nim wrapper on top of `git bisect run` that does exactly that. The point is, it's automated, and for all but the simplest bugs it helps.
