### PR TITLE
fix #19349 incompatible type when mixing float32 and cfloat in generics

### LINKED ISSUE #19349: "incompatible type" when mixing float32 and cfloat in generics
Mixing `float32` and `cfloat` can sometimes lead to a strange error that exposes the generated C code.

### Example
```nim
type
  Vec3[T: SomeNumber] = object
    arr: array[3, T]

var 
  cfloatArr: array[3, array[3, cfloat]]
  cfloatSeq = newSeq[Vec3[cfloat]]()
for row in cfloatArr:
  cfloatSeq.add(Vec3[float32](arr: [row[0], row[1], row[2]]))
echo cfloatSeq
```

### Current Output
```
/Users/sekao/.cache/nim/nim_misc_d/@mnim_misc.nim.c:449:40: error: assigning to 'tyObject_Vec3__a2hI8d3noWjXtSOVv1UfRA' (aka 'struct tyObject_Vec3__a2hI8d3noWjXtSOVv1UfRA') from
      incompatible type 'tyObject_Vec3__c79bdlxFEYQ7KlCcTS4NeNw' (aka 'struct tyObject_Vec3__c79bdlxFEYQ7KlCcTS4NeNw')
                                cfloatSeq__nim95misc_37->data[T5_] = T4_;
```

### Expected Output
```
@[(arr: [0.0, 0.0, 0.0]), (arr: [0.0, 0.0, 0.0]), (arr: [0.0, 0.0, 0.0])]
```

### Additional Information
The code works in nim 1.2.6.

```
$ nim -v
Nim Compiler Version 1.6.2 [MacOSX: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf
```

### PR DESCRIPTION
**Pull request by bung87**
fix #19349

### CODE REVIEW

**Comment by arnetheduck** [comment]
backport pls

**Comment by arnetheduck** [comment]
@narimiran ^

**Comment by narimiran** [comment]
> @narimiran ^

Done.
