### ISSUE TITLE
C++ codegen: importcpp breaks for generic types.

### ISSUE THREAD

**Issue by nigredo-tori** [nim-lang/Nim#7653]
This code:
```nim
type Vector* {.importcpp: "std::vector", header: "<vector>", nodecl.} [T] = object
proc mkVector*[T]: Vector[T] {.importcpp: "std::vector<'*0>()", header: "<vector>", constructor, nodecl.}

proc foo(): Vector[cint] =
  mkVector[cint]()

proc bar(): Vector[cstring] =
  mkVector[cstring]()
```
, when compiled with
```sh
nim cpp codegen_bug.nim
```
, produces incorrect return type in the generated C++ code (both functions are declared to return `vector<int>`):
```cpp
typedef std::vector<int>  TY_lsra5sU08ga9bO3llT5YRoA;

/* irrelevant code here */

N_LIB_PRIVATE N_NIMCALL(TY_lsra5sU08ga9bO3llT5YRoA, foo_mtEaLGWplUQxutU9alIWbUw)(void) {
	TY_lsra5sU08ga9bO3llT5YRoA result;
	nimfr_("foo", "codegen_bug.nim");
	nimln_(5, "codegen_bug.nim");
	result = std::vector<int>();
	popFrame();
	return result;
}

N_LIB_PRIVATE N_NIMCALL(TY_lsra5sU08ga9bO3llT5YRoA, bar_mtEaLGWplUQxutU9alIWbUw_2)(void) {
	TY_lsra5sU08ga9bO3llT5YRoA result;
	nimfr_("bar", "codegen_bug.nim");
	nimln_(8, "codegen_bug.nim");
	result = std::vector<NCSTRING>();
	popFrame();
	return result;
}
```
, resulting in this error:
```
/home/dmitry/work/tmp/nimcache/codegen_bug.cpp: In function ‘TY_lsra5sU08ga9bO3llT5YRoA bar_mtEaLGWplUQxutU9alIWbUw_2()’:
/home/dmitry/work/tmp/nimcache/codegen_bug.cpp:78:33: error: no match for ‘operator=’ (operand types are ‘TY_lsra5sU08ga9bO3llT5YRoA {aka std::vector<int>}’ and ‘std::vector<char*>’)
  result = std::vector<NCSTRING>();
```

Nim version: devel (5d13e3f28bf479cd1d59fdec7f34847df988416c)

**Comment by cooldome** [comment]
hitted as well. Works for 0.18, definitely a regression. I suspect changes by zah for cpp codegen with static[T]

**Comment by cooldome** [comment]
Ah, before it was std::vector<NCSTRING> directly, now it is TY_sighash and hash only covers std::vector, NCSTRING is not part of the hash

**Comment by cooldome** [comment]
Introduced in https://github.com/nim-lang/Nim/commit/121b9e26fb9d1ae6037c806dbb12a3ae0e26ded6

offending line: https://github.com/nim-lang/Nim/commit/121b9e26fb9d1ae6037c806dbb12a3ae0e26ded6#diff-4ce3eb003e2427b6f7d23ad0b6231706R848

It is not clear whether it is imported type does not follow generic type conventions or it is signature computation is what is wrong

**Comment by Araq** [comment]
> It is not clear whether it is imported type does not follow generic type conventions or it is signature computation is what is wrong

I don't know either. Maybe it uses the wrong signature.

**Comment by nigredo-tori** [comment]
I've poked around a bit. `Vector[cstring]` produces a `PType` structure like this:
```nim
tyGenericInst 
  tyGenericBody Vector 
    tyGenericParam T
    tyObject Vector
  tyCString cstring
  tyObject Vector
```

Meanwhile, in `hashType`:
```nim
case t.kind
...
of tyAlias, tySink, tyGenericInst, tyUserTypeClasses:
  c.hashType t.lastSon, flags
  return
```

That is, type parameters are not used for hash calculation.

One of these must be incorrect, but I'm not familiar enough with compiler internals to say which.
