### ISSUE TITLE
C compiler error with inline and a proc field in an object 

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14758]
Sorry, couldn't make a better title.

### Example
```nim
type
  SomePointer = ref | ptr | pointer | proc
  Option[T] = object
    when T is SomePointer:
      val: T
    else:
      val: T
      has: bool

proc some*[T](val: T): Option[T] {.inline.} =
  when T is SomePointer:
    result.val = val
  else:
    result.has = true
    result.val = val

proc none*(T: typedesc): Option[T] {.inline.} =
  discard

type
  Events = object
    # remove this proc and it works
    cb: proc (guild: Option[Guild])
  
  Guild = ref object

proc channelPinsUpdate*() =
  var guild = none Guild
  guild = some Guild()

channelPinsUpdate()
```

### Current Output
```
/home/dian/.cache/nim/tt_d/@mtt.nim.c: In function ‘some__xq16iLMQ9bb9atkSAOGgyfnQtt’:
/home/dian/.cache/nim/tt_d/@mtt.nim.c:147:11: error: ‘tyObject_Option__tEu09c5iyZ7d63kPxo53T0Q’ has no member named ‘has’
  147 |  (*Result).has = 0;
      | 
```

### Additional information
Regression - works just fine on 1.2.0

```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-06-22
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 451129de4213805b74b1635565d998904d705458
active boot switches: -d:release -d:danger
```

**Comment by ghost** [comment]
`git bisect` told me that the first bad commit is f71f8b0239e3d6aff75390075bba13a62c292422 which is of course not the root cause.

**Comment by ghost** [comment]
Reduced even further:
```nim
type
  SomePointer = ref | ptr | pointer | proc
  Option[T] = object
    when T is SomePointer:
      val: T
    else:
      val: T
      has: bool

proc some*[T](val: T): Option[T] {.inline.} =
  when T is SomePointer:
    result.val = val
  else:
    result.has = true
    result.val = val

proc none*(T: typedesc): Option[T] {.inline.} =
  discard

type
  Events = object
    # remove this proc and it works
    cb: proc (guild: Option[Guild])
  
  Guild = ref object

proc channelPinsUpdate*() =
  var guild = none Guild
  guild = some Guild()

channelPinsUpdate()
```

Works on v1.2.0, not on v1.2.2, will try to bisect this

**Comment by ghost** [comment]
Ran git bisect - b35d370d885b07d3f4eca527197f42f532bdcf64 is the first bad commit
```git
commit b35d370d885b07d3f4eca527197f42f532bdcf64
Author: Andreas Rumpf <rumpf_a@web.de>
Date:   Tue May 19 21:42:53 2020 +0200

    specialize genericReset (#14398)
    
    * progress
    * make tests green
    * maybe we also want to reset pointers, dunno
    * progress
    * cleanup; fixes #13879 [backport:1.2]

 compiler/ccgexprs.nim | 46 ++++++++++++-------------
 compiler/ccgreset.nim | 94 +++++++++++++++++++++++++++++++++++++++++++++++++++
 compiler/cgen.nim     |  8 +++--
 lib/system/gc_ms.nim  |  2 +-
 4 files changed, 124 insertions(+), 26 deletions(-)
 create mode 100644 compiler/ccgreset.nim
bisect run success
```

**Comment by ghost** [comment]
Works with ``--gc:arc`` of course :)

**Comment by Araq** [comment]
Workaround:

```nim

type
  Guild = ref object
  Events = object
    # remove this proc and it works
    cb: proc (guild: Option[Guild])
```

Indicating some really troubled generic instantiation issue...

**Comment by bung87** [comment]
works on current devel https://github.com/nim-lang/Nim/commit/be18f4e513799de186e6de53f32c9488b19f1ec7

**Comment by ringabout** [comment]
Yeah, it works with ORC and the devel branch has already defaulted to ORC.

**Comment by bung87** [comment]
oh, I see , refc still fails.

**Comment by bung87** [comment]
var guild = none Guild -> typdesct[Guild] -> Guild, is tyForward

indeed it is tyForward

workaround is delcare Guild first like [Araq](https://github.com/Araq) said.

**Comment by bung87** [comment]
better remove lables or just close this, as there're already issues in same case `tyForward` things.
