### PR TITLE
Fix small typo in the documentation

### LINKED ISSUE #7363: [Regression] Missing type declarations in C code if members are used in {.emit.}
Introduced in 70b28a39fedfe030ac4e1615d32328d7ffd3f79d.

```nim
type Foo {.exportc.} = object
  a: cint
proc f(foo: ptr Foo): cint =
  {.emit: "`result` = `foo`->a;".}
echo f(nil)
```
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test.o /Users/yglukhov/nimcache/test.c' failed with exit code: 1

/Users/yglukhov/nimcache/test.c:82:14: error: incomplete definition of type 'struct Foo'
        result = foo->a;
                 ~~~^
/Users/yglukhov/nimcache/test.c:24:16: note: forward declaration of 'struct Foo'
typedef struct Foo Foo;
               ^
1 error generated.
```
@cooldome, can we fix it so that `{.exportc.}` types are always declared completely?

### LINKED ISSUE #7394: Should `use x` be a comment in the example code for Var statements?
See:  [stmts.txt#L148](https://github.com/nim-lang/Nim/blob/a0b547001bdf1ec583c4fdc3b2a635da6d2bdfa1/doc/manual/stmts.txt#L148)

### PR DESCRIPTION
**Pull request by cabhishek**
Fixes #7363

### CODE REVIEW

**Comment by Araq** [comment]
Not really a typo, but ok.
