### ISSUE TITLE
Borrow with distinct float don't compile

### ISSUE THREAD

**Issue by ClementJnc** [nim-lang/Nim#1127]
The code 

``` nimrod
type
    a = distinct float
    b = distinct float
    c = distinct float

proc `+` (aa:a, bb:b): c {.borrow.}

var xa = 5.a
var xb = 6.b
var xc:c = xa + xb

echo xc.float
```

doesn't compile.

It gives (with option --parallelBuild:1)

```
/etc/nimrod.cfg(37, 2) Hint: added path: '/home/cj/.babel/pkgs/gtk2-1.0' [Path]
/etc/nimrod.cfg(37, 2) Hint: added path: '/home/cj/.babel/pkgs/aporia-0.2.0' [Path]
/etc/nimrod.cfg(37, 2) Hint: added path: '/home/cj/.babel/pkgs/jester-0.1.0' [Path]
/etc/nimrod.cfg(37, 2) Hint: added path: '/home/cj/.babel/pkgs/' [Path]
Hint: used config file '/etc/nimrod.cfg' [Conf]
Hint: system [Processing]
Hint: test_borrow [Processing]
/tmp/nimcache/test_borrow.c: In function ‘test_borrowInit’:
/tmp/nimcache/test_borrow.c:82:15: error: expected expression before ‘)’ token
  xc_82025 = (()(xa_82017) + ()(xb_82021));
               ^
Error: execution of an external program failed
```

It works with 0.9.2.
