### ISSUE TITLE
xmlparser does not compile on devel

### ISSUE THREAD

**Issue by pgkos** [nim-lang/Nim#14805]
Calling `rawData` from xmlparser causes a gcc compilation error.

### Example
```nim
import parsexml

var x: XmlParser
discard x.rawData()
```

or without importing anything

```nim
type Foo = object
  a: string

proc bar(f: var Foo): lent string =
  result = f.a

var foo = Foo(a: "")
echo bar(foo)
```

### Current Output
```
/home/pgkos/.cache/nim/bug_d/@mbug.nim.c: In function ‘NimMainModule’:
/home/pgkos/.cache/nim/bug_d/@mbug.nim.c:240:50: error: lvalue required as unary ‘&’ operand
  240 |  T1_ = rawData__tRCHvnc9cLagcEJwWBb3fhAparsexml((&(&x__cPZNa6xEymIK9coPig9bRHuw)));
      |                                                  ^
```

### Additional Information
```
$ nim -v
Nim Compiler Version 1.3.5 [Linux: amd64]
Compiled at 2020-06-25
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 32f335f594d7007fabe4232a63f51137d7fb6cc1
active boot switches: -d:release
```

**Comment by ghost** [comment]
Can confirm with clang on Linux:
```
/home/dian/.cache/nim/seq_d/@mseq.nim.c:238:50: error: cannot take the address of an rvalue of type 'tyObject_XmlParser__VUwAch81P9c4ST1PUfTYo0g *' (aka 'struct tyObject_XmlParser__VUwAch81P9c4ST1PUfTYo0g *')
        T1_ = rawData__tRCHvnc9cLagcEJwWBb3fhAparsexml((&(&x__1RQ9cr16DizgApzfYXHh28A)));
                                                        ^ ~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.
```

**Comment by ghost** [comment]
`git bisect` showed b3029ba2139a018946218e1917918d1a1ef019e2 as the first bad commit.
