### PR TITLE
Allow {.doctype.} in Nim 1.6 w/o implementation

### PR DESCRIPTION
**Pull request by a-mr**
`doctype` pragma, implemented in Nim 2.0 (#20252), fails to compile with Nim 1.6.
This stub does not implement it. It is just to be able to have the same source code with `doctype` for Nim 1.6 & 2.0.

### CODE REVIEW

**Comment by Araq** [comment]
@narimiran what do you think?

**Comment by narimiran** [comment]
> @narimiran what do you think?

It seems reasonable. Merging.
