### PR TITLE
potential fix for C++ codegen with ARC/ORC and goto exceptions fixes #21579, fixes #21862

### LINKED ISSUE #21579: C++ compilation error with `exceptions:goto` + ARC/ORC when compiling basic branching code
### Description

This code fails to compile on devel and on 1.6.12 with `nim cpp --exceptions:goto --mm:orc file.nim`:

```nim
proc mysubstr: string =
  discard

proc findNormalized(x: string): int =
  discard

proc addfor =
  var x = findNormalized mysubstr()
  if x != 0: 
    echo "hi there :)"

addfor()
```

This is minimized from the original code sent to me in private from the Telegram (see https://t.me/nim_lang/139761 for the context). Minimization chain: `asynchttpserver` -> (dump async code) -> inline `asyncfutures` -> stacktrace generation code -> `strutils.%` -> `strutils.addf`

A "shallowly" minimized version is also available for making sure my repro didn't miss the original issue:
```nim
# example.nim
import asyncdispatch, asynchttpserver

let server = newAsyncHttpServer()

proc cb(req: Request): Future[void] {.async.} =
    discard

waitFor server.serve(Port(2060), cb, "127.0.0.1")
```

Both examples work with `--mm:refc` instead of ARC/ORC

### Nim Version

Nim Compiler Version 1.9.1 [Linux: amd64]
Compiled at 2023-03-28
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: 2315b01ae691e5e9e54fdfdfb4642c8fbc559e48
active boot switches: -d:release

### Current Output
With clang (for a better error)

```text

/home/dian/Projects/NimExperiments/here22/@mttt.nim.cpp:71:30: error: cannot jump from this goto statement to its label
        if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
                                    ^
/home/dian/Projects/NimExperiments/here22/@mttt.nim.cpp:73:5: note: jump bypasses variable initialization
        NI x = T2_;
           ^
/home/dian/Projects/NimExperiments/here22/@mttt.nim.cpp:72:5: note: jump bypasses variable initialization
        NI T2_ = findNormalized__ttt_3(colontmpD_);
           ^
1 error generated.
Error: execution of an external compiler program 'clang++ -c -std=gnu++17 -funsigned-char  -pthread  -O3 -fno-ident   -I/home/dian/Things/nim/lib -I/home/dian/Projects/NimExperiments -o /home/dian/Projects/NimExperiments/here22/@mttt.nim.cpp.o /home/dian/Projects/NimExperiments/here22/@mttt.nim.cpp' failed with exit code: 1
```

### Expected Output

```text
Successful compilation
```

### Possible Solution

_No response_

### Additional Information

I also found out that https://github.com/nim-lang/Nim/issues/13998 fails to compile with `nim cpp --mm:orc --exceptions:goto file.nim` with the same error.

### LINKED ISSUE #21862: cpp + arc causing  error: cannot jump from this goto statement to its label
### Description

This code:

```nim
import std/[asyncdispatch]

proc main()  =
  proc callMe() {.async.} =
    echo "hello"
    await sleepAsync(1000)
    echo "world"
  waitFor callMe()


main()
```

Fails when compiling with arc and cpp with the error below.

However, when compiling it with `refc` or `c` it works fine

I have seen this error before without using async but couldnt reproduce it anymore but I dont think it's async-related.

### Nim Version

```
Nim Compiler Version 1.9.3 [MacOSX: amd64]
Compiled at 2023-05-18
Copyright (c) 2006-2023 by Andreas Rumpf

git hash: b03ea373a2c8b3d189aad88a12e0735081157d5e
```

### Current Output

```
CC: helloworld.nim
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:714:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:692:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                    /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:292:152: error: cannot jump from this goto statement to its label
                        if ((parentpos) < ((NI)0) || (parentpos) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(parentpos, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA5_;
                                                                                                                                                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:294:37: note: jump bypasses variable initialization
                        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T6_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (parentpos)));
                                                         ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:287:83: error: cannot jump from this goto statement to its label
                        if (nimSubInt(pos, ((NI)1), &TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) { raiseOverflow(); goto LA5_;
                                                                                                       ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:294:37: note: jump bypasses variable initialization
                        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T6_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (parentpos)));
                                                         ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:289:7: note: jump bypasses variable initialization
                        NI parentpos = (NI)((NI64)((NI)(TM__f2bNHCHm2LvO7iSrwQtdiQ_9)) >> (NU64)(((NI)1)));
                           ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:273:132: error: cannot jump from this goto statement to its label
        if ((pos) < ((NI)0) || (pos) > ((NI)IL64(9223372036854775807))){ raiseRangeErrorI(pos, ((NI)0), ((NI)IL64(9223372036854775807))); goto LA1_;
                                                                                                                                          ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp:275:35: note: jump bypasses variable initialization
        tyTuple__o0bBbmYdV2dERI6OV5Sxaw* T2_ = X5BX5D___pureZasyncdispatch_u179((&heap_p0), ((NI) (pos)));
                                         ^
3 errors generated.
        ^
Error: execution of an external compiler program 'clang++ -c -std=gnu++17 -funsigned-char  -pthread   -I/Volumes/Store/Nim/lib -I/Volumes/Store/Dropbox/Code/Projects/nimlab/lab -o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp.o /Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@scollections@sheapqueue.nim.cpp' failed with exit code: 1


/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:690:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:676:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:674:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:672:31: error: cannot jump from this goto statement to its label
                if (NIM/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:649:30: error: cannot jump from this goto statement to its label
        if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
                                    ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:650:82: note: jump bypasses variable initialization
        tyObject_Env_asyncmacrodotnim_callMeX20X28AsyncX29___AY9bkjC9b9bvoV0KM3Lo2giow* blitTmp = colonenv__2;
                                                                                        ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@mhelloworld.nim.cpp:643:30: error: cannot jump from this goto statement to its label
        if (NIM_UNLIKELY(*nimErr_)) goto LA1_;
                                    ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
                                                              ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:651:31: error: cannot jump from this goto statement to its label
                if (NIM_UNLIKELY(*nimErr_)) goto LA5_;
                                            ^
/Volumes/Store/Dropbox/Code/Projects/nimlab/lab/nimcache/helloworld/@m..@s..@s..@s..@s..@sNim@slib@spure@sasyncfutures.nim.cpp:716:49: note: jump bypasses variable initialization
                tyObject_FutureError__KNjPKOMkVazrylBrW4Vdnw* blitTmp_2 = err;
```

### Expected Output

_No response_

### Possible Solution

Use `inc p.splitDecls` in the scenario that triggers this? Doenst feel like a good solution though

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by heterodoxic**
fixes #21579
fixes #21862

### CODE REVIEW

**Comment by juancarlospaco** [comment]
Put it in a single line IMHO, 1 condition per line seems like too much.

**Comment by bung87** [comment]
could you add test file?

**Comment by heterodoxic** [comment]
> Put it in a single line IMHO, 1 condition per line seems like too much.

Sorry for my rather latish reply: I do not like the formatting myself, but I thought I merely followed the style that was already present there.

**Comment by heterodoxic** [comment]
> could you add test file?

Sorry for my rather latish reply: yes, absolutely, will do ASAP!
