### ISSUE TITLE
Cannot build on RHEL7/GCC 4.8.5 - undefined reference to __builtin_smulll_overflow

### ISSUE THREAD

**Issue by Nindaleth** [nim-lang/Nim#17040]
I'm putting together Nim RPM packages for my team's internal use. I've built some packages in the 1.0.x line, then took a break and now I'd like to continue with the 1.4.x line. The team uses VM images that try to reflect the customer production environment; in this case it's RHEL7; there's quite an old GCC version which may be causing issues now, but I could build with it previously in 1.0.x.

Yes, I should probably just pull an official release and package the binaries from there, but I was wondering if this is something planned (GCC 4.8.5 supports C++11, so it's not _that_ old) or it could still work.

### Current Output
(please check whether the problem still exists in git head before posting,)

```
# tar xfJ nim-${nim_version}.tar.xz
# cd nim-${nim_version}
# sh build.sh
(...)
gcc -w -fmax-errors=3 -O3 -fno-strict-aliasing -fno-ident -Ic_code -c c_code/2_2/@mnim.nim.c -o c_code/2_2/@mnim.nim.o
gcc -o bin/nim c_code/1_2/stdlib_assertions.nim.o c_code/2_2/stdlib_dollars.nim.o c_code/1_2/stdlib_formatfloat.nim.o c_code/2_2/stdlib_io.nim.o c_code/2_2/stdlib_system.nim.o c_code/2_2/stdlib_parseutils.nim.o c_code/2_2/stdlib_math.nim.o c_code/1_2/stdlib_algorithm.nim.o c_code/2_2/stdlib_unicode.nim.o c_code/2_2/stdlib_strutils.nim.o c_code/2_2/stdlib_pathnorm.nim.o c_code/2_2/stdlib_posix.nim.o c_code/2_2/stdlib_times.nim.o c_code/2_2/stdlib_os.nim.o c_code/1_2/stdlib_hashes.nim.o c_code/1_2/stdlib_strtabs.nim.o c_code/1_2/stdlib_sets.nim.o c_code/2_2/@mpathutils.nim.o c_code/2_2/@mropes.nim.o c_code/1_2/stdlib_tables.nim.o c_code/1_2/@mlineinfos.nim.o c_code/2_2/@mplatform.nim.o c_code/1_2/@mprefixmatches.nim.o c_code/1_2/@mnimpaths.nim.o c_code/2_2/stdlib_strformat.nim.o c_code/2_2/stdlib_terminal.nim.o c_code/2_2/@moptions.nim.o c_code/2_2/@mstrutils2.nim.o c_code/2_2/@mmsgs.nim.o c_code/1_2/@mcondsyms.nim.o c_code/2_2/stdlib_streams.nim.o c_code/2_2/stdlib_cpuinfo.nim.o c_code/2_2/stdlib_osproc.nim.o c_code/2_2/stdlib_sha1.nim.o c_code/2_2/stdlib_lexbase.nim.o c_code/1_2/stdlib_parsejson.nim.o c_code/2_2/stdlib_json.nim.o c_code/2_2/@mextccomp.nim.o c_code/1_2/@mwordrecg.nim.o c_code/2_2/@mnimblecmd.nim.o c_code/2_2/stdlib_parseopt.nim.o c_code/1_2/@mincremental.nim.o c_code/1_2/@midents.nim.o c_code/1_2/@midgen.nim.o c_code/1_2/@mint128.nim.o c_code/1_2/@mast.nim.o c_code/2_2/@mcommands.nim.o c_code/2_2/@mllstream.nim.o c_code/1_2/@mnimlexbase.nim.o c_code/2_2/@mlexer.nim.o c_code/1_2/@mparser.nim.o c_code/2_2/@mrenderer.nim.o c_code/1_2/@mfilters.nim.o c_code/1_2/@mfilter_tmpl.nim.o c_code/1_2/@msyntaxes.nim.o c_code/1_2/stdlib_intsets.nim.o c_code/1_2/@mrodutils.nim.o c_code/2_2/@mastalgo.nim.o c_code/1_2/@mtrees.nim.o c_code/2_2/@mtypes.nim.o c_code/1_2/@mbtrees.nim.o c_code/1_2/stdlib_md5.nim.o c_code/1_2/@mmodulegraphs.nim.o c_code/1_2/@mmagicsys.nim.o c_code/1_2/@mbitsets.nim.o c_code/1_2/@mnimsets.nim.o c_code/2_2/@msemfold.nim.o c_code/2_2/@mmodulepaths.nim.o c_code/1_2/@mvmdef.nim.o c_code/1_2/@msemdata.nim.o c_code/1_2/@mlinter.nim.o c_code/1_2/@mnimfix@sprettybase.nim.o c_code/1_2/@mlookups.nim.o c_code/1_2/@msemtypinst.nim.o c_code/1_2/@mparampatterns.nim.o c_code/1_2/@mlowerings.nim.o c_code/2_2/@msigmatch.nim.o c_code/1_2/@mimporter.nim.o c_code/1_2/@mprocfind.nim.o c_code/2_2/@mpragmas.nim.o c_code/1_2/@mreorder.nim.o c_code/1_2/@mpasses.nim.o c_code/1_2/@msaturate.nim.o c_code/1_2/@mguards.nim.o c_code/1_2/@mtypeallowed.nim.o c_code/1_2/@misolation_check.nim.o c_code/1_2/@mvarpartitions.nim.o c_code/1_2/@msighashes.nim.o c_code/1_2/@mliftdestructors.nim.o c_code/1_2/@msempass2.nim.o c_code/1_2/@mcgmeth.nim.o c_code/1_2/@mliftlocals.nim.o c_code/1_2/@mlambdalifting.nim.o c_code/1_2/@mclosureiters.nim.o c_code/1_2/@mtransf.nim.o c_code/1_2/@mvmgen.nim.o c_code/2_2/@mvmdeps.nim.o c_code/1_2/@mvmmarshal.nim.o c_code/2_2/@mgorgeimpl.nim.o c_code/1_2/@mmacrocacheimpl.nim.o c_code/1_2/@mvmprofiler.nim.o c_code/1_2/@mevaltempl.nim.o c_code/1_2/@mvmconv.nim.o c_code/2_2/@mvm.nim.o c_code/1_2/@maliases.nim.o c_code/1_2/@mpatterns.nim.o c_code/1_2/@msemmacrosanity.nim.o c_code/1_2/@mpluginsupport.nim.o c_code/1_2/@mplugins@slocals.nim.o c_code/1_2/@mplugins@sitersgen.nim.o c_code/1_2/@mplugins@sactive.nim.o c_code/1_2/@mspawn.nim.o c_code/2_2/@msem.nim.o c_code/1_2/@mccgutils.nim.o c_code/1_2/@mtreetab.nim.o c_code/2_2/@mndi.nim.o c_code/1_2/@mcgendata.nim.o c_code/1_2/@mccgmerge.nim.o c_code/1_2/@menumtostr.nim.o c_code/1_2/@mdfa.nim.o c_code/1_2/@moptimizer.nim.o c_code/1_2/@minjectdestructors.nim.o c_code/1_2/@msemparallel.nim.o c_code/2_2/stdlib_dynlib.nim.o c_code/2_2/@mcgen.nim.o c_code/1_2/@mmodules.nim.o c_code/2_2/@mscriptconfig.nim.o c_code/2_2/@mnimconf.nim.o c_code/1_2/@mpassaux.nim.o c_code/1_2/@mdepends.nim.o c_code/1_2/@msourcemap.nim.o c_code/1_2/@mjsgen.nim.o c_code/1_2/@m..@slib@spackages@sdocutils@srstast.nim.o c_code/1_2/@m..@slib@spackages@sdocutils@srst.nim.o c_code/1_2/@m..@slib@spackages@sdocutils@shighlite.nim.o c_code/2_2/@m..@slib@spackages@sdocutils@srstgen.nim.o c_code/1_2/stdlib_xmltree.nim.o c_code/1_2/stdlib_base64.nim.o c_code/1_2/stdlib_uri.nim.o c_code/1_2/stdlib_cgi.nim.o c_code/1_2/@mtypesrenderer.nim.o c_code/1_2/@mrenderverbatim.nim.o c_code/2_2/stdlib_globs.nim.o c_code/2_2/@mdocgen.nim.o c_code/2_2/@mdocgen2.nim.o c_code/2_2/@mmain.nim.o c_code/2_2/@mcmdlinehelper.nim.o c_code/2_2/stdlib_browsers.nim.o c_code/2_2/@mnim.nim.o -ldl -lm -lrt
c_code/2_2/stdlib_system.nim.o: In function `newSeq':
stdlib_system.nim.c:(.text+0x844b): undefined reference to `__builtin_smulll_overflow'
stdlib_system.nim.c:(.text+0x8466): undefined reference to `__builtin_saddll_overflow'
c_code/2_2/stdlib_system.nim.o: In function `newSeqRC1':
stdlib_system.nim.c:(.text+0x970d): undefined reference to `__builtin_smulll_overflow'
stdlib_system.nim.c:(.text+0x9728): undefined reference to `__builtin_saddll_overflow'
c_code/2_2/stdlib_system.nim.o: In function `nimNewSeqOfCap':
stdlib_system.nim.c:(.text+0x9829): undefined reference to `__builtin_smulll_overflow'
stdlib_system.nim.c:(.text+0x9840): undefined reference to `__builtin_saddll_overflow'
collect2: error: ld returned 1 exit status


# gcc --version
gcc (GCC) 4.8.5 20150623 (Red Hat 4.8.5-44)
Copyright (C) 2015 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

### Expected Output

```
: SUCCESS
```
build finishes, nim binary is generated, I can proceed with `bin/nim c -d:release koch` and `./koch tools`

### Additional Information

1.0.10 is the last Nim release that builds on that GCC. Tried a couple of 1.2.x, 1.4.2, 1.4.4 RC and 1.5.1-devel nightly, none of them build.

EDIT: project readme states that `A C compiler such as gcc 3.x/later` is required to build the sources, thus either there is an alternative procedure available to build releases on older GCCs (in that case please point me to it, I'd love to try it) or this is a build regression.

**Comment by mratsim** [comment]
There is a `builtinOverflow` defined that is on by default with GCC/Clang: https://github.com/nim-lang/Nim/blob/3fb5157ab1b666a5a5c34efde0f357a82d433d04/lib/system/arithm.nim#L20-L24

Not sure how to `undef` though, I expect they also control this `NIM_EmulateOverflowChecks` flag https://github.com/nim-lang/Nim/blob/e1129749207d25597e81fe06cd7e3099b5ecb61e/lib/nimbase.h#L575-L593

**Comment by timotheecour** [comment]
use `-d:nimEmulateOverflowChecks`, it controls `NIM_EmulateOverflowChecks` 

but in future we should support `--minGccVersion:x.y.z`, `--minOSXVersion`, `--minLinuxVersion` etc, see https://github.com/timotheecour/Nim/issues/565

**Comment by Araq** [comment]
Compile with `-d:nimEmulateOverflowChecks`.
