### ISSUE TITLE
regression(1.2 => 1.4 onwards): Block-local ref types with the same name lead to bad codegen: `no member named`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#15526]
basically same as fixed https://github.com/nim-lang/Nim/issues/5170 but for ref types

### Example
```nim
when true: # D20201008T141857
  block:
    type Foo = ref object
      x1: int
    let f1 = Foo(x1: 1)
  block:
    type Foo = ref object
      x2: int
    let f2 = Foo(x2: 2)
```

### Current Output
```
@mt11116.nim.c:422:10: error: no member named 'x2' in 'struct tyObject_FoocolonObjectType___ktEbVfDBqcSUCx9b6syN8LA'
                (*T4_).x2 = ((NI) 2);
```

### Expected Output
works

### Additional Information
basically same as fixed https://github.com/nim-lang/Nim/issues/5170 (which was fixed) but for ref types
* nim devel 1.3.7 3eaacac2303ab9fc1aef62208a112fae0ddd9152 and prior
* EDIT: very similar to https://github.com/nim-lang/Nim/issues/17162

**Comment by timotheecour** [comment]
further info: it's a regression, it used to work in 1.2.0 (through 1.2.8)

## with ref object
works in vm, js
fails in RT
```nim
when true:
  # D20201008T141857
  template fn() =
    block:
      type Foo = ref object
        x1: int
      let f1 = Foo(x1: 1)
      echo f1.x1
    block:
      type Foo = ref object
        x2: int
      let f2 = Foo(x2: 2)
      echo f2.x2
  static: fn()
  fn()
```


## with object
works in vm, js, RT
```nim
when defined case5:
  template fn() =
    block:
      type Foo = object
        x1: int
      let f1 = Foo(x1: 1)
      echo f1.x1
    block:
      type Foo = object
        x2: int
      let f2 = Foo(x2: 2)
      echo f2.x2
  static: fn()
  fn()
```

**Comment by timotheecour** [comment]
git bisect shows it's caused by 2629d61 #15091; so this is in fact the same root cause as https://github.com/nim-lang/Nim/issues/17162 (we could close 1 of them as duplicate, or better yet, fix the regression)

**Comment by ringabout** [comment]
@timotheecour 
not sure whether it is a regression, please double check the first example on Nim playground.

**Comment by timotheecour** [comment]
@xflywind indeed, https://github.com/nim-lang/Nim/issues/15526#issuecomment-784656202 was a regression but top example is not a regression, so there's a partial regression here; in any case i'm fixing all these here: https://github.com/nim-lang/Nim/pull/17710
