### ISSUE TITLE
A seq of variable objects with Option type fields crashes the compiler

### ISSUE THREAD

**Issue by leventea** [nim-lang/Nim#13495]
A sequence of variable objects with Option type fields made the compiler spit out GCC errors when I attempted to echo them out. The sequence was made compile time and assigned to a constant variable. It works perfectly when the sequence is populated at runtime, as expected. 

I observed that it only errors out if there's an unset Option type field on a unused case branch.
The size of the sequence does not seem to matter.

I'm using version 1.0.6 of the Nim compiler and version 9.2.0 of GCC.

### Reproduction code
```nim
import options

type
  TestKind = enum
    KindOne, KindTwo

  Repro = object
    case kind: TestKind
    of KindOne:
      kindOneField: string
      
    of KindTwo:
      kindTwoField: string
      kindTwoOption: Option[string]

proc reproProc(): seq[Repro] {.compileTime.} =
  result.add Repro(kind: KindOne,
                   kindOneField: "kindOneFieldValue")

const seq = reproProc()

echo seq
```

### Error
```
/home/user/.cache/nim/main_d/@mmain.nim.c:118:239: error: extra brace group at end of initializer
  118 | } TM__V45tF8B8NBcxFcjfe7lhBw_7 = {{1, 1 | NIM_STRLIT_FLAG}, {{((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_5), ((tyEnum_TestKind__IgVPOhEsq9bLWCskCndZO5w) 0), ((NimStringDesc*) &TM__V45tF8B8NBcxFcjfe7lhBw_6), ((NimStringDesc*) NIM_NIL), {((NimStringDesc*) NIM_NIL), NIM_FALSE}}}};
      |                                                                                                                                                                                                                                               ^
/home/user/.cache/nim/main_d/@mmain.nim.c:118:239: note: (near initialization for ‘TM__V45tF8B8NBcxFcjfe7lhBw_7.data[0]’)
```

**Comment by SolitudeSF** [comment]
compiles fine on `devel` (and 9.2.0 gcc)

**Comment by leventea** [comment]
> compiles fine on `devel` (and 9.2.0 gcc)

Just tried it, runs fine for me too.
