### ISSUE TITLE
broken C generated: member reference base type is not a structure or union

### ISSUE THREAD

**Issue by mrwonko** [nim-lang/Nim#9655]
I get an error compiling this code:

### Example
```
import asynchttpserver, asyncdispatch
import strformat

proc main() =
    let local = "123"

    proc serveIndex(req: Request) {.async, gcsafe.} =
        await req.respond(Http200, &"{local}")

    proc serve404(req: Request) {.async, gcsafe.} =
        echo req.url.path
        await req.respond(Http404, "not found")

    proc serve(req: Request) {.async, gcsafe.} =
        let handler = case req.url.path:
            of "/":
                serveIndex
            else:
                serve404
        await handler(req)
    
    let server = newAsyncHttpServer()
    waitFor server.serve(Port(8080), serve, address = "127.0.0.1")

when isMainModule:
    main()
```

### Current Output
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/willi/.choosenim/toolchains/nim-0.19.0/lib -o /Users/willi/.cache/nim/repro_d/destiny_builder_repro.c.o /Users/willi/.cache/nim/repro_d/destiny_builder_repro.c' failed with exit code: 1

/Users/willi/.cache/nim/repro_d/destiny_builder_repro.c:1311:87: error: member reference base type 'tyObject_FuturecolonObjectType__te3W2Tqi7xuJ7rlPtg9al5w *(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ *)' (aka 'struct tyObject_FuturecolonObjectType__te3W2Tqi7xuJ7rlPtg9al5w *(struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ *)') is not a structure or union
                                asgnRef((void**) (&(*colonenvP_).handler1.ClE_0), serve404_cMCA9cDbggCQHYvdZAVf2hQ.ClE_0);
                                                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
/Users/willi/.cache/nim/repro_d/destiny_builder_repro.c:1312:68: error: member reference base type 'tyObject_FuturecolonObjectType__te3W2Tqi7xuJ7rlPtg9al5w *(tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ *)' (aka 'struct tyObject_FuturecolonObjectType__te3W2Tqi7xuJ7rlPtg9al5w *(struct tyObject_Request_1Wfxxtqzahm0R6lueM9aQmQ *)') is not a structure or union
                                (*colonenvP_).handler1.ClP_0 = serve404_cMCA9cDbggCQHYvdZAVf2hQ.ClP_0;
                                                               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^~~~~~
2 errors generated.
```

### Additional Information

This is on macOS X Mojave on stable 0.19.

**Comment by skilchen** [comment]
This slight modification of your code seems to work:
```nim
import asynchttpserver, asyncdispatch
import strformat


proc main() =
  let local = "123"

  proc serveIndex(req: Request) {.async.} =
    await req.respond(Http200, &"{local}")

  proc serve404(req: Request) {.async.} =
    echo req.url.path
    await req.respond(Http404, "not found")

  proc serve(req: Request) {.async.} =
    var handler: proc(req: Request): Future[void]
    case req.url.path
    of "/":
      handler = serveIndex
    else:
      handler = serve404
    await handler(req)
  
  let server = newAsyncHttpServer()
  waitFor server.serve(Port(8080), serve, address = "127.0.0.1")

when isMainModule:
  main()
```

**Comment by cooldome** [comment]
Does it work with Nim 0.18? Look like a similar issue to https://github.com/nim-lang/Nim/issues/9441

**Comment by mrwonko** [comment]
Same issue in Nim 0.18.0.

And you're right, @cooldome, using a case statement instead of a case expression works around the issue, which will do for now but I dislike it.
