### ISSUE TITLE
Codegen error with no generic brackets + converters

### ISSUE THREAD

**Issue by metagn** [nim-lang/Nim#16105]
It appears converters have some kind of return type inference but it gives a codegen error when used without specifying `auto` generic params. This is a very old regression; it worked in 0.15.0, but not in 0.16.0.

### Example
```nim
type Foo[T] = object
  field: T

converter toFoo[T](x: T): Foo[T] = Foo[T](field: x)

echo Foo(3)
# works: echo Foo[auto](3)
```

### Current Output
```
/usercode/nimcache/@min.nim.c: In function 'NimMainModule':
/usercode/nimcache/@min.nim.c:173:45: error: incompatible type for argument 1 of 'dollar___5foMV9cu7pf79czQPPDJStkw'
  T1_[0] = dollar___5foMV9cu7pf79czQPPDJStkw(T2_);
                                             ^~~
In file included from /usercode/nimcache/@min.nim.c:11:0:
/usercode/nimcache/@min.nim.c:65:41: note: expected 'tyObject_Foo__HINQAux9cuKp59agW9clxkqlA {aka struct tyObject_Foo__HINQAux9cuKp59agW9clxkqlA}' but argument is of type 'tyObject_Foo__6fdnw5OZ3KKmqOCzgedHBA {aka struct tyObject_Foo__6fdnw5OZ3KKmqOCzgedHBA}'
 N_LIB_PRIVATE N_NIMCALL(NimStringDesc*, dollar___5foMV9cu7pf79czQPPDJStkw)(tyObject_Foo__HINQAux9cuKp59agW9clxkqlA x);
                                         ^
/playground/nim/lib/nimbase.h:252:44: note: in definition of macro 'N_NIMCALL'
 #  define N_NIMCALL(rettype, name) rettype name /* no modifier */
                                            ^~~~
```

If you switch `echo Foo(3)` to just `let x = Foo(3)`, you get a simpler error:

```
/usercode/nimcache/@min.nim.c:157:28: error: incompatible types when assigning to type 'tyObject_Foo__HINQAux9cuKp59agW9clxkqlA {aka struct tyObject_Foo__HINQAux9cuKp59agW9clxkqlA}' from type 'tyObject_Foo__6fdnw5OZ3KKmqOCzgedHBA {aka struct tyObject_Foo__6fdnw5OZ3KKmqOCzgedHBA}'
  x__EGWKGClUlppqAonIP2rgfg = toFoo__jgdu5UVwV9bZ0qWLw2QaraQ(((NI) 3));
```

### Expected Output
```
(field: 3)
```
or some kind of Nim error

This fails from 0.16.0 through the nightly of 1.5.1 I have from 2020-11-12, but works from 0.13.0 to 0.15.0. Older versions not tested.

**Comment by cooldome** [comment]
Fully instantiated type is required:
```nim
echo Foo[int](3)
echo Foo[auto](3)
```
Compiler should reject it in sempass
