### PR TITLE
One more fix. Fixes #7363

### LINKED ISSUE #7363: [Regression] Missing type declarations in C code if members are used in {.emit.}
Introduced in 70b28a39fedfe030ac4e1615d32328d7ffd3f79d.

```nim
type Foo {.exportc.} = object
  a: cint
proc f(foo: ptr Foo): cint =
  {.emit: "`result` = `foo`->a;".}
echo f(nil)
```
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test.o /Users/yglukhov/nimcache/test.c' failed with exit code: 1

/Users/yglukhov/nimcache/test.c:82:14: error: incomplete definition of type 'struct Foo'
        result = foo->a;
                 ~~~^
/Users/yglukhov/nimcache/test.c:24:16: note: forward declaration of 'struct Foo'
typedef struct Foo Foo;
               ^
1 error generated.
```
@cooldome, can we fix it so that `{.exportc.}` types are always declared completely?

### PR DESCRIPTION
**Pull request by cooldome**

### CODE REVIEW

**Comment by Araq** [comment]
Er, were is the RFC for this new feature? Can't say I like it too much, pragmas depending on the parser, seems messy.

> The `emit` pragma now supports backticking of Nim expressions

**Comment by yglukhov** [comment]
Thinking further about it, this makes copypasting C/JS code into `emit` even more hard...

**Comment by cooldome** [comment]
The target audience does not seem to be interested. Closing...

**Comment by Araq** [comment]
Well please don't mix bugfixes with new features.
