### ISSUE TITLE
[Regression] Invalid C code for _ symbol inside jester routes

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#5452]
```nim
import jester, asyncdispatch
routes:
    get "/":
        let _ = 5
```
```
/Users/yglukhov/nimcache/test.c:190:4: error: expected member name or ';' after declaration specifiers
NI 275435;
~~ ^
/Users/yglukhov/nimcache/test.c:190:3: error: expected ';' at end of declaration list
NI 275435;
  ^
  ;
/Users/yglukhov/nimcache/test.c:787:18: error: expected ';' after expression
                                (*colonenvP_).275435 = ((NI) 5);
                                             ^
                                             ;
/Users/yglukhov/nimcache/test.c:787:26: error: expression is not assignable
                                (*colonenvP_).275435 = ((NI) 5);
                                             ~~~~~~~ ^
/Users/yglukhov/nimcache/test.c:1320:141: error: expected identifier
TM_ipcYmBC9bj9a1BW35ABoB1Kw_0[11].offset = offsetof(Env_Projectsslashnimslashlibslashpureslashasyncmacrodotnim378__kiwfgk1z9ctEwOSJ2p5df2Q, 275435);
                                                                                                                                            ^
5 errors generated.
```

Also it looks like lambda lifting is incorrect because it "captures" things that it should not.

**Comment by yglukhov** [comment]
Introduced in 4c5ecb46b0b1bd14af80e7bf234e92e1bf85b28a
