### ISSUE TITLE
typedef is generated for .importcpp enums

### ISSUE THREAD

**Issue by endragor** [nim-lang/Nim#4145]
Fresh devel started generating `typedef` code for imported enums. This breaks a lot of existing wrapper code.

Sample (run with `nim cpp -r`):
```nim
{.emit: """/*TYPESECTION*/
enum class Color {
  Red, Green, Blue
};
""".}

type
  Color {.importcpp: "Color", nodecl, pure.} = enum
    Red,
    Green,
    Blue

proc getColor(): Color =
  return Color.Red

# sample.cpp:15:13: error: typedef redefinition with different types ('NU8' (aka 'unsigned char') vs 'Color')
# typedef NU8 Color;
#             ^
```

Seems to be caused by c912ae6
