### ISSUE TITLE
bad c codegen for iterators

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#6274]
the following seems to lead to the generation of duplicate symbol declaration by the c backend:
``` Nim
# main.nim
import sequtils, math


iterator foo(): int {. closure .} =
  yield 1

proc trans(i: iterator: int): iterator: int = 
  return iterator(): int =
    for e in i():
      yield e

discard toSeq(trans(foo)())
```
compiler invocation output:

```
$ nim c main.nim
Hint: used config file '/home/jesse/nim/config/nim.cfg' [Conf]
Hint: system [Processing]
Hint: main [Processing]
Hint: sequtils [Processing]
Hint: math [Processing]
CC: main
CC: stdlib_system
Error: execution of an external compiler program 'gcc -c  -w  -I/home/jesse/nim/lib -o /home/jesse/src/blockout/nimcache/main.o /home/jesse/src/blockout/nimcache/main.c' failed with exit code: 1

/home/jesse/src/blockout/nimcache/main.c: In function ‘NimMainModule’:
/home/jesse/src/blockout/nimcache/main.c:438:46: error: redeclaration of ‘foo’ with no linkage
    Env_maindotnim__cOB9cSUxMscMrXXzJN9aCuwA* foo;
                                              ^
/home/jesse/src/blockout/nimcache/main.c:435:46: note: previous declaration of ‘foo’ was here
    Env_maindotnim__cOB9cSUxMscMrXXzJN9aCuwA* foo;
                                              ^
$ nim --version
Nim Compiler Version 0.17.0 (2017-05-17) [Linux: amd64]
Copyright (c) 2006-2017 by Andreas Rumpf

git hash: d3f0f87e81e262ee25fd528aae5b6db0bdf78d5e

```

**Comment by narimiran** [comment]
This compiles fine in Nim v0.19.0. Can be closed.

---

For the completeness sake, running the code like is written above will give you infinite loop. The example below works fine:

```nim
import sequtils, math


iterator foo(): int {. closure .} =
  for i in 1 .. 10:
    yield i

proc trans(i: iterator: int): iterator: int = 
  result = iterator(): int =
    for e in i():
      yield e


let bar = trans(foo)

echo bar()
echo bar()
echo bar()
echo bar()

# echoes: 1; 2; 3; 4
```
