### ISSUE TITLE
C compiler error when using the result of a template in the subscript operator

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#20302]
### What happened?

This code shows a C compiler error during compilation:

```nim
template minIndexByIt: untyped =
  var other = 3
  other

proc main() =
  var hlibs = @["hello", "world", "how", "are", "you"]
  let res = hlibs[minIndexByIt()]
  echo res

main()
```

### Nim Version

Nim Compiler Version 1.7.1 [Linux: amd64]
Compiled at 2022-09-04
Copyright (c) 2006-2022 by Andreas Rumpf

git hash: 23e0160af283bb0bb573a86145e6c1c792780d49
active boot switches: -d:release

### Current Standard Output Logs

```shell
/home/dian/.cache/nim/tast_d/@mtast.nim.c:134:5: error: redefinition of 'otherX60gensym0_'
        NI otherX60gensym0_;
           ^
/home/dian/.cache/nim/tast_d/@mtast.nim.c:133:5: note: previous definition is here
        NI otherX60gensym0_;
```

### Additional Information

This code worked in Nim 1.6.6

**Comment by hamidb80** [comment]
works on nim 1.7.1 `2022-07-17`

**Comment by ghost** [comment]
@hamidb80 with ARC?

**Comment by ghost** [comment]
ah, I created a duplicate issue by accident, see https://github.com/nim-lang/Nim/issues/20303
