### ISSUE TITLE
Regression: compile error using `when/elif/else`  and `typedesc` in template

### ISSUE THREAD

**Issue by arkanoid87** [nim-lang/Nim#19426]
Please help me find a better title for this issue.

The example compiles with 1.4.8 and returns error with 1.6.0.
Bisect has found 2aba116bbc8c1a595e49c8a703f2b8aecd7e8eda as first bad commit

Tested with both orc and refc

https://play.nim-lang.org/#ix=3MTf

### Example
```nim
type
  MyInt = object
    bitWidth: int

template toRealType*(t: MyInt): typedesc =
  when t.bitWidth == 32: int32
  elif t.bitWidth == 64: int64
  else: {.error.}

proc doFail(T: typedesc): T = default(T)

proc test =
  const myInt = MyInt(bitWidth:32)
  discard doFail(toRealType(myInt))

test()
```

### Current Output
```
Error: unhandled exception: field 'sym' is not accessible for type 'TNode' using 'kind = nkIdent' [FieldDefect]
```

### Expected Output
```
compilation successful
```

### Additional Information
It's a regression:

- 1.4.8: compiles successfully
- 1.6.0  up to devel: compilation error

### Bisect result
first bad commit: [2aba116bbc8c1a595e49c8a703f2b8aecd7e8eda] when statements branches exit early (#17143)
