### ISSUE TITLE
[Regression] Bad C codegen for generic code

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#6889]
Introduced in eae1aaa37728578bf93263b0ca24064a31ca4b16
```nim
proc createProgressSetterWithPropSetter[T](setter: proc(v: T)) = discard

type A = distinct array[4, float32]
type B = distinct array[3, float32]

type Foo[T] = tuple
    setter: proc(v: T)

proc getFoo[T](): Foo[T] = discard

createProgressSetterWithPropSetter(getFoo[A]().setter)
createProgressSetterWithPropSetter(getFoo[B]().setter)
```
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test3.o /Users/yglukhov/nimcache/test3.c' failed with exit code: 1

/Users/yglukhov/nimcache/test3.c:108:61: error: passing 'tyProc_iEerKTmFwmz8BafX9c9cnTjw' to parameter of incompatible type 'tyProc_neJuG7CV47Ms8LHWVUlW7w'
        createProgressSetterWithPropSetter_3zP4IeMjU2QRTtnI9cRon0Q(T2_.Field0);
                                                                   ^~~~~~~~~~
/Users/yglukhov/nimcache/test3.c:55:107: note: passing argument to parameter 'setter' here
N_NIMCALL(void, createProgressSetterWithPropSetter_3zP4IeMjU2QRTtnI9cRon0Q)(tyProc_neJuG7CV47Ms8LHWVUlW7w setter) {
                                                                                                          ^
1 error generated.
```
