### ISSUE TITLE
[Regression] Missing type declarations in C code if members are used in {.emit.}

### ISSUE THREAD

**Issue by yglukhov** [nim-lang/Nim#7363]
Introduced in 70b28a39fedfe030ac4e1615d32328d7ffd3f79d.

```nim
type Foo {.exportc.} = object
  a: cint
proc f(foo: ptr Foo): cint =
  {.emit: "`result` = `foo`->a;".}
echo f(nil)
```
```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/yglukhov/Projects/nim/lib -o /Users/yglukhov/nimcache/test.o /Users/yglukhov/nimcache/test.c' failed with exit code: 1

/Users/yglukhov/nimcache/test.c:82:14: error: incomplete definition of type 'struct Foo'
        result = foo->a;
                 ~~~^
/Users/yglukhov/nimcache/test.c:24:16: note: forward declaration of 'struct Foo'
typedef struct Foo Foo;
               ^
1 error generated.
```
@cooldome, can we fix it so that `{.exportc.}` types are always declared completely?

**Comment by cooldome** [comment]
Hi Yuriy,
I think exportc is irrelevant here, what is actually needs to be patched is genEmit. I will have a look

**Comment by cooldome** [comment]
I have a patch, I will prepare PR later today

**Comment by Zdreni** [comment]
I think this may be related to that issue. Seems that ptr or var reference to structure type doesn't cause generation of C code for that type. For example:

```
type stbtt_hheap_chunk {.exportc.} = object
    next: ptr stbtt_hheap_chunk

proc test(x: ptr stbtt_hheap_chunk) =
    discard
```

However adding next line:
```
var testHeapChunk: stbtt_hheap_chunk
```
causes code to be generated

**Comment by cooldome** [comment]
Hi Zdreni,
Your example compiles without an issue. Exclusion of stbtt_hheap_chunk is intensional in this case, you are not using it

**Comment by cooldome** [comment]
Zdreni, maybe you have more comprehensive example

**Comment by yglukhov** [comment]
The talk is probably about ttf lib which is exactly the reason why I filed this issue.

**Comment by Zdreni** [comment]
Sorry, example was fixed. This was a bit shortened extraction of code from ttf (0.2.4) nimble package.
The error should be: "incomplete definition of type 'struct stbtt_hheap_chunk'"

**Comment by Zdreni** [comment]
After fix, the issue still remains in other form. Just use additional level of indirection:
```
type stbtt_hheap_chunk {.exportc.} = object
    next: ptr stbtt_hheap_chunk

type stbtt_hheap {.exportc.} = object
    head: ptr stbtt_hheap_chunk

proc test(x: ptr stbtt_hheap) =
   {.emit: """
   if (`x`->head->next) {} else {}
   """.}
```

Causes:
`error: incomplete definition of type 'struct stbtt_hheap_chunk'`

**Comment by Zdreni** [comment]
I also need to mention that simple tracking of field names mentioned in emit possibly may not help in corner cases where name of field is generated by macro/concatenating two strings. TBH, I doubt there is a reason for optimizing out structures, that may be possible used in emit blocks.

**Comment by cooldome** [comment]
checking...

**Comment by cooldome** [comment]
I suggest I'll add support for expression backticking in emit pragma:
Then the following is going to work:
```
proc test(x: ptr stbtt_hheap) =
   {.emit: """
   if (`x.head.next`) {} else {}
   """.}
```
and also
```
proc test(x: ptr stbtt_hheap) =
   {.emit: """
   if (`x.head`->.next) {} else {}
   """.}
```
It is useful feature on its own plus it will allow for Nim trace type usage properly.

Let me know if you are ok with the proposal.

**Comment by yglukhov** [comment]
@cooldome, I'm ok with your proposal, although I think `exportc` is a nice indicator for the type to be defined. I mean why else would you want to place `exportc` on it?

**Comment by Zdreni** [comment]
Proposed solution with expression backticking, however, will not work on lot of existing code, leaving packages build broken.

**Comment by cooldome** [comment]
@yglukhov

Yuriy,
What you are asking is not unreasonable, but it has nothing to do with this regression. Compiler did ignore not used types before and it ignores them now, no changes to ``exportc`` treatment were introduced either.
I suggest raising a separate feature request. The implementation would require codegen pass to walk the type definitions (currently type sections completely ignored) and check their flags.

**Comment by cooldome** [comment]
I have submittted the PR with backticking of expressions

**Comment by yglukhov** [comment]
Seems like this issue was closed by irrelevant PR. Also note, that this can be easily worked around by adding
```
(void)sizeof(`MyType`);
```
to the `emit` pragma.

**Comment by cooldome** [comment]
I have raised separate feature request #7448 
Mean while I suggest using proposed workaround and close this issue.

**Comment by Araq** [comment]
Too much of a fringe case.
