### ISSUE TITLE
static[T] with string constant

### ISSUE THREAD

**Issue by PavelVozenilek** [nim-lang/Nim#1064]
This compiles and works OK with the 0.9.3 executable downloaded from nimbuild right now:
```
proc foo(a: static[int]) =
  echo a

const x : int = 999
foo(x)
```
This works too:
```
proc foo2(a: static[string]) =
  echo a

foo2("oops")
```
This, however, fails to compile by gcc:
```
proc foo2(a: static[string]) =
  echo a

const y : string = "oops"
foo2(y)
```
with error
> gcc.exe -c  -w  -IO:\nimrod\0.9.3\Nimrod\lib -o o:\nimrod\0.9.3\nimrod\bin\nimcache\a.o o:\nimrod\0.9.3\nimrod\bin\nimca
che\a.c
o:\nimrod\0.9.3\nimrod\bin\nimcache\a.c: In function 'aInit':
o:\nimrod\0.9.3\nimrod\bin\nimcache\a.c:92:2: error: too many arguments to function 'foo2_82033'
  foo2_82033(((NimStringDesc*) &TMP126));
  ^
In file included from o:\nimrod\0.9.3\nimrod\bin\nimcache\a.c:8:0:
o:\nimrod\0.9.3\nimrod\bin\nimcache\a.c:51:17: note: declared here
 N_NIMCALL(void, foo2_82033)(void) {
                 ^
O:\nimrod\0.9.3\Nimrod\lib/nimbase.h:142:55: note: in definition of macro 'N_NIMCALL'
 #  define N_NIMCALL(rettype, name) rettype __fastcall name
                                                       ^
Error:  execution of an external program failed; rerun with --parallelBuild:1 to see the error message

**Comment by yglukhov** [comment]
Can't reproduce it with latest devel. Close?

**Comment by dom96** [comment]
Same. Closing.
