### PR TITLE
IC: green tests

### PR DESCRIPTION
**Pull request by Araq**
To do:

- [ ] fix arraymancer regression
- [ ] make tgeneric test case green
- [ ] write a method test case (make the methods `.inline` for good measure)
- [ ] EDIT(timotheecour) figure out how to un-disable tests/dll/nimhcr_integration.nim

### CODE REVIEW

File: tests/dll/nimhcr_integration.nim [hunk 1]
```diff
@@ -1,5 +1,5 @@
 discard """
-  disabled: "openbsd"
+  disabled: "true"
```
Comment (timotheecour) [inline tests/dll/nimhcr_integration.nim:2]: I hope that's temporary?

Comment (Araq) [reply tests/dll/nimhcr_integration.nim:2]: I don't know, I don't understand why my minor refactoring breaks this test and I invested 2 hours already. Be my guest.

Comment (timotheecour) [reply tests/dll/nimhcr_integration.nim:2]: I can reproduce the CI failure locally (with the test undisabled).

possibly related to:
* https://github.com/nim-lang/Nim/issues/11974
* https://github.com/nim-lang/Nim/issues/15081
* https://github.com/nim-lang/Nim/pull/16223  (comment regarding HCR test failing)

I also spent time to fix an HCR issue (which enabled that integration test in the first place) eg in https://github.com/nim-lang/Nim/pull/16329.

It could be just 1 underlying bug (HCR related). However it'd be really really nice to fix it instead of disabling it

/cc @zah since you introduced the feature, do you have any idea where to look?

Comment (Araq) [reply tests/dll/nimhcr_integration.nim:2]: I can reproduce it too on my local machine but that doesn't help.

**Comment by Vindaar** [comment]
@Araq The arraymancer regression you mention is:

https://github.com/mratsim/Arraymancer/issues/505

With the additional comments and the likely related issue https://github.com/status-im/nim-blscurve/pull/133 any ideas on a fix?
For arraymancer we've introduced a workaround, but it seems to be a bigger issue.

**Comment by Araq** [comment]
The other comparable problems were all simply serious bugs in the C code.

**Comment by mratsim** [comment]
There's no bug in the C code, you can't split CPU features sensitive stuff into separate Nim files anymore and use localpassc (Weave https://github.com/mratsim/weave/issues/171#issuecomment-1007914278 and Constantine: https://github.com/mratsim/constantine/blob/master/constantine/arithmetic/assembly/limbs_asm_mul_x86_adx_bmi2.nim#L30) or nim.cfg anymore (Arraymancer: https://github.com/mratsim/Arraymancer/blob/master/nim.cfg#L83)

**Comment by Araq** [comment]
There is no logic that "inlines" Nim modules and the existing logic didn't change. I'm not saying "there is no problem here", I'm saying "please give me a reduced test case".

**Comment by ringabout** [comment]
A reduced example

https://github.com/xflywind/reduced

*example.nim*
```nim
import macros

type
  MicroKernel = object
    cpu_simd: CPUFeatureX86

  CPUFeatureX86* = enum
    x86_AVX512

{.localpassC:"-mavx512f -mavx512dq".}

func x86_ukernel*(cpu: CPUFeatureX86, T: typedesc): MicroKernel =
  result.cpu_simd = cpu

{.pragma: x86_type, byCopy, header:"<x86intrin.h>".}
{.pragma: x86, noDecl, header:"<x86intrin.h>".}
type
  m512d {.importc: "__m512d", x86_type.} = object
    raw: array[8, float64]

func mm512_setzero_pd(): m512d {.importc: "_mm512_setzero_pd", x86.}

macro ukernel_generator(simd: static CPUFeatureX86): untyped =
  result = newStmtList()
  block:
    let ukernel_name = newIdentNode("gebb_ukernel_" & $float64 & "_" & $simd)
    result.add quote do:
      proc `ukernel_name`[ukernel: static MicroKernel]() =
        let AB = ukernel_simd_impl(ukernel)

macro ukernel_simd_impl(ukernel: static MicroKernel): untyped =
  result = newStmtList()
  var rAB = nnkBracket.newTree()
  var rABi = nnkBracket.newTree()
  rABi.add genSym(nskVar, "AB" & $0 & "__" & $0)
  rAB.add rABi

  var declBody = newStmtList()
  let ab = rAB[0][0]
  declBody.add quote do:
    var `ab` = mm512_setzero_pd()

  result = quote do:
    `declBody`
    `rAB`

ukernel_generator(x86_AVX512)

{.experimental: "dynamicBindSym".}

macro dispatch_general*(
    ukernel: static MicroKernel,
  ): untyped =
  result = newStmtList()
  let simdTag = $ukernel.cpu_simd
  let ukernel_name = bindSym("gebb_ukernel_" & $float64 & "_" & simdTag)
  result.add quote do:
    `ukernel_name`[ukernel]()
```

*test.nim*

```nim
import example

const ukernel = x86_AVX512.x86_ukernel(float64)
dispatch_general(ukernel)
```

`nim c test.nim` works in 1.4.8 but breaks in devel.

```
D:/mingw64/lib/gcc/x86_64-w64-mingw32/9.2.0/include/avx512fintrin.h:325:1: error: inlining failed in call to always_inline '_mm512_setzero_pd': target specific option mismatch
  325 | _mm512_setzero_pd (void)
      | ^~~~~~~~~~~~~~~~~
C:\Users\blue\nimcache\test_d\@mtest.nim.c:654:11: note: called from here
  654 |  AB13_1 = _mm512_setzero_pd();
```

**Comment by ringabout** [comment]
see also https://github.com/nim-lang/Nim/pull/19363
