### ISSUE TITLE
"incompatible type" when mixing float32 and cfloat in generics

### ISSUE THREAD

**Issue by oakes** [nim-lang/Nim#19349]
Mixing `float32` and `cfloat` can sometimes lead to a strange error that exposes the generated C code.

### Example
```nim
type
  Vec3[T: SomeNumber] = object
    arr: array[3, T]

var 
  cfloatArr: array[3, array[3, cfloat]]
  cfloatSeq = newSeq[Vec3[cfloat]]()
for row in cfloatArr:
  cfloatSeq.add(Vec3[float32](arr: [row[0], row[1], row[2]]))
echo cfloatSeq
```

### Current Output
```
/Users/sekao/.cache/nim/nim_misc_d/@mnim_misc.nim.c:449:40: error: assigning to 'tyObject_Vec3__a2hI8d3noWjXtSOVv1UfRA' (aka 'struct tyObject_Vec3__a2hI8d3noWjXtSOVv1UfRA') from
      incompatible type 'tyObject_Vec3__c79bdlxFEYQ7KlCcTS4NeNw' (aka 'struct tyObject_Vec3__c79bdlxFEYQ7KlCcTS4NeNw')
                                cfloatSeq__nim95misc_37->data[T5_] = T4_;
```

### Expected Output
```
@[(arr: [0.0, 0.0, 0.0]), (arr: [0.0, 0.0, 0.0]), (arr: [0.0, 0.0, 0.0])]
```

### Additional Information
The code works in nim 1.2.6.

```
$ nim -v
Nim Compiler Version 1.6.2 [MacOSX: amd64]
Compiled at 2021-12-17
Copyright (c) 2006-2021 by Andreas Rumpf
```

**Comment by Vindaar** [comment]
As this seems to be somewhat related to https://github.com/nim-lang/Nim/issues/19374 I checked whether the fix to #16246, specifically:
https://github.com/nim-lang/Nim/commit/e8dad482a309b1c33056aba22550d691845414d7#diff-23877fff4d200f490b74503f9db6fced353182598a5b72e8925598f2430bd6b0R1148-R1154
caused this regression. 

That seems to be the case. Taking out the added code makes the example compile again.

**Comment by ringabout** [comment]
Works in 1.4.8 not in 1.6.0
