### ISSUE TITLE
execvpe not available on older linux versions

### ISSUE THREAD

**Issue by gradha** [nim-lang/Nim#1734]
With the goal of building linux binaries able to run on any distros I've been playing with installing older debian versions. There is a problem with execvpe not being available on older libc versions. During the csources build phase you get:

```
c_code/2_2/stdlib_osproc.o: In function `startprocessafterfork_139807':
stdlib_osproc.c:(.text+0x976): undefined reference to `execvpe'
collect2: ld returned 1 exit status
```

execpve works on libc 2.11.3-4 (debian6) but fails on 2.7-18lenny7 (debian5) and older.

It seems that the solution is to [write our own execpve](http://www.digitalmars.com/d/archives/digitalmars/D/9132.html). Before doing any work, I would like to know if such patches are welcome at all (or no support is provided for older libc versions) and if yes, how should this be patched. My guess is that since autoconf is to be avoided a nimrod version of execvpe would be written and used instead of the C version.

Also, the [macosx and freebsd ports don't use execvpe](https://github.com/Araq/Nimrod/blob/3ce2fd6677938e29e22e592822d408af2d240107/lib/pure/osproc.nim#L819), maybe their solution could be used on Linux too?

**Comment by pb-cdunn** [comment]
I think the issue was **gcc**, not the O/S. I still see that on Centos7 with `gcc/4.9.2`, but it worked fine with `gcc/6.3.0`.

**Comment by pb-cdunn** [comment]
Actually, I do find `execvpe()` in glibc, in all Gnulib versions [after 2.10](https://www.gnu.org/software/gnulib/manual/html_node/execvpe.html). The real problem is that `execvpe()` is only GNU, so it is not declared in `<unistd.h>` unless `_GNU_SOURCE` is defined, even though it actually exists in the glibc shared library. (See also #3759, where execvpe() is used only for GNU).

I see 3 possible solutions:

A. Do not use `execvpe()` at all. (It is not used for non-GNU anyway.)
B. Declare `execvpe()` explicitly, for GNU builds.
C. Define `_GNU_SOURCE`.

For (B):

    extern int execvpe(char const* file, char* const argv[], char* const envp[]);

(C) is best, but it needs to be defined before all other includes. I do not see how to accomplish that with Nim (except by the user).

**Comment by pb-cdunn** [comment]
More info. `execvpe()` became available in glibc-2.11:

* https://github.com/sulix/bingcc/blob/master/glibc_ver.h#L179

**Comment by Araq** [comment]
But people also like to link against "musl" or others and who knows whether they use _GNU_SOURCE. (A) seems the better option, but as I said, it's a risky change.
