### ISSUE TITLE
C source compile error when using compile time variable

### ISSUE THREAD

**Issue by vegansk** [nim-lang/Nim#3845]
Inspired by #3844. The problem is in the last line.

``` nimrod
import macros

var x {.compiletime.} = 1

macro foo() : untyped =
  inc(x)
  echo $x
  result = newStmtList()

foo()
foo()
echo $x
```

fails to compile c source but not nim source:

```
2
3
CC: nimtests_test_macro
Error: execution of an external compiler program 'gcc -c  -w  -I/home/vega/work/nim/Nim/lib -o /home/vega/work/nim/nimtests/issues/3844/nimcache/nimtests_test_macro.o /home/vega/work/nim/nimtests/issues/3844/nimcache/nimtests_test_macro.c' failed with exit code: 256

/home/vega/work/nim/nimtests/issues/3844/nimcache/nimtests_test_macro.c: In function ‘test_macroInit000’:
/home/vega/work/nim/nimtests/issues/3844/nimcache/nimtests_test_macro.c:108:21: error: ‘x_98001’ undeclared (first use in this function)
  LOC1 = nimIntToStr(x_98001);
                     ^
/home/vega/work/nim/nimtests/issues/3844/nimcache/nimtests_test_macro.c:108:21: note: each undeclared identifier is reported only once for each function it appears in
```

**Comment by narimiran** [comment]
Works with Nim devel 1.1.1.
