### ISSUE TITLE
Nim fails to compile on MacOSX 10.10 because of sys/random.h header included in std/sysrand

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#17370]
Got this bug report from my friend

### Current Output
```
CC: stdlib_sysrand.nim
Error: execution of an external compiler program 'clang -c  -w -ferror-limit=3 -O3  -I/Users/vlad/projects/Nim/lib -I/Users/vlad/projects/Nim/compiler -o /Users/vlad/projects/Nim/nimcache/r_macosx_amd64/stdlib_sysrand.nim.c.o /Users/vlad/projects/Nim/nimcache/r_macosx_amd64/stdlib_sysrand.nim.c' failed with exit code: 1

In file included from /Users/vlad/projects/Nim/nimcache/r_macosx_amd64/stdlib_sysrand.nim.c:8:
/usr/include/sys/random.h:37:32: error: unknown type name 'u_int'
void read_random(void* buffer, u_int numBytes);
                               ^
/usr/include/sys/random.h:38:33: error: unknown type name 'u_int'
void read_frandom(void* buffer, u_int numBytes);
                                ^
/usr/include/sys/random.h:39:33: error: unknown type name 'u_int'
int  write_random(void* buffer, u_int numBytes);
                                ^
3 errors generated.
FAILURE
```

### Expected Output
Successful compilation

### Additional information
CPython seems to have hit the same problem before - https://bugs.python.org/issue29057.

If you check https://opensource.apple.com/source/xnu/xnu-4903.270.47/bsd/sys/random.h.auto.html you'll see that sys/random.h is available from macOS 10.12 and up.

One way to fix this would be to use the same iOS impl. for macOS (secRandomCopyBytes is available in macOS 10.10+).  

Another way is to check if we have macOS 10.12 and up (via https://opensource.apple.com/source/xnu/xnu-4903.270.47/EXTERNAL_HEADERS/Availability.h.auto.html) and use generic urandom on older macOS versions.

As a temporary workaround it's possible to replace line 240 in `lib/sytd/sysrand.nim` with `elif false` and on line 61 `  batchImplOs = false`, then the compilation succeeds (because then the generic urandom impl. is used).

Git hash - 7937abab4439ef2cd317d4ef70551327f55711e1

**Comment by ghost** [comment]
Rust implementation does it that way - it checks if `getentropy` exists (with dlsym - ), and if it doesn't - the call uses `/dev/urandom` instead.

https://github.com/rust-lang/rust/issues/70179

https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/rand.rs#L130
https://github.com/rust-lang/rust/blob/master/library/std/src/sys/unix/weak.rs#L29

**Comment by ringabout** [comment]
hope this issue is fixed

**Comment by ringabout** [comment]
It should be fixed, feel free to reopen if not.

**Comment by iffy** [comment]
I just ran into this issue trying to install 1.6.0 on macOS 10.10.5. Yes, it's an old computer, but one I'd like to still use. If 10.10 should still be supported, I can look into submitting a patch.
