### ISSUE TITLE
emit/importc regression in devel/1.6.4rc

### ISSUE THREAD

**Issue by PMunch** [nim-lang/Nim#19483]
Noticed this when I created [this issue ](https://github.com/nim-lang/Nim/issues/19482). The example from that issue compiles on 1.6.2, but fails on 1.6.4 and devel with:
```
/home/peter/.cache/nim/dctest_d/stdlib_system.nim.c:6634:53: error: unknown type name ‘Vector2’
 6634 | N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___dctest_10)(Vector2 x, Vector2 y) {
      |                                                     ^~~~~~~
/home/peter/.cache/nim/dctest_d/stdlib_system.nim.c:6634:64: error: unknown type name ‘Vector2’
 6634 | N_LIB_PRIVATE N_NIMCALL(NIM_BOOL, eqeq___dctest_10)(Vector2 x, Vector2 y) {
      |                                                                ^~~~~~~
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3   -I'/home/peter/.choosenim/toolchains/nim-#version-1-6/lib' -I/tmp -o /home/peter/.cache/nim/dctest_d/stdlib_system.nim.c.o /home/peter/.cache/nim/dctest_d/stdlib_system.nim.c' failed with exit code: 1
```

Compiling with 1.4.6 yields the same error, so it seems to have been fixed before 1.6.0 but regressed between 1.6.2 and 1.6.4.

**Comment by narimiran** [comment]
My bisecting on the `version-1-6` branch has pointed to this PR: https://github.com/nim-lang/Nim/pull/19363/files (cc @xflywind)

**Comment by ringabout** [comment]
Not sure whether it is actually fixed in 1.6.0 which compiles accidentally and still cannot work due to https://github.com/nim-lang/Nim/issues/19482

#19363 reverted a troublesome change in 1.6.0 

Maybe it shouldn't block 1.6.4 release.
