### PR TITLE
fixes #22913; fixes #12985 differently push-ing pragma exportc genera…

### LINKED ISSUE #12985: regression (1.0.4): `{.push exportc.}` wrongly affects generic instantiations, causing codegen errors
regression: `{.push exportc.}` doesn't work anymore in some cases, causing `reset` to be cgen'd without mangling, which causes c compilation error as soon as multiple types are invovled. EDIT: root cause seems to be that exportc applies recursively in some cases (when it involves generics that have at least 1 pragma)

### Example
after upgrading to latest nim, my project failed; after a painful reduction it boils down to this:
```nim
  {.push exportc.}
  proc foo1() =
    var s1 = "bar"
    reset(s1)
    var s2 = @[1]
    reset(s2)
  {.pop.}
```

### Current Output
```
/Users/timothee/git_clone/nim/timn/build/nimcache/@mt0854.nim.c:77:17: error: conflicting types for 'reset'
N_NIMCALL(void, reset)(tySequence__qwqHTkRvwhrRyENtudHQ7g** obj);
                ^
/Users/timothee/git_clone/nim/timn/build/nimcache/@mt0854.nim.c:75:17: note: previous declaration is here
N_NIMCALL(void, reset)(NimStringDesc** obj);
```

### Expected Output
works

### Possible Solution
* `{.push exportc.}` should not be recursive and only apply to top-level
* alternatively if push is meant to be recursive, we need a non-recursive variant, eg:
`{.pushNodepth exportc.}`

### Additional Information
D20191227T162616

* the snippet above was working in version 1.0.4; EDIT: whether it's a regression or not is debatable given that the underlying root cause
* fails in latest devel b67dea7a33d24cd54afa8bd37677d066f4be0da1
* `proc foo1()  {.exportc.}` instead of `{.push exportc.}` does not have that bug

### LINKED ISSUE #22913: push-ing pragma exportc generates invalid C identifiers
### Description

Compiles fine

```nim
type r* = object

proc foo(): r {.exportc: "$1".} =
  echo result
```

Fails:

```nim
type r* = object

{.push exportc: "$1".}
proc foo(): r =
  echo result
{.pop.}
```

Compilation command:

```bash
nim -r c repro.nim
```

### Nim Version

```
Nim Compiler Version 2.0.0 [MacOSX: arm64]
Compiled at 2023-08-02
Copyright (c) 2006-2023 by Andreas Rumpf

active boot switches: -d:release
```

### Current Output

Fails with an invalid generated C symbol:

```text
CC: ../../nim-2.0.0/lib/std/objectdollar.nim
/Users/turbo/.cache/nim/repro_d/@m..@s..@snim-2.0.0@slib@sstd@sobjectdollar.nim.c:142:10: error: expected ';' at end of declaration
        NI count`gensym1;
                ^
                ;
/Users/turbo/.cache/nim/repro_d/@m..@s..@snim-2.0.0@slib@sstd@sobjectdollar.nim.c:149:7: error: expected ';' after expression
        count`gensym1 = ((NI)0);
             ^
             ;
/Users/turbo/.cache/nim/repro_d/@m..@s..@snim-2.0.0@slib@sstd@sobjectdollar.nim.c:149:7: error: expected expression
```

### Expected Output

none, successful compilation

### Possible Solution

_No response_

### Additional Information

_No response_

### PR DESCRIPTION
**Pull request by ringabout**
…tes invalid C identifiers

fixes #22913
fixes #12985 differently

`{.push.} now does not apply to generic instantiations`

### CODE REVIEW

File: compiler/pragmas.nim [hunk 1]
```diff
@@ -1313,7 +1313,7 @@ proc implicitPragmas*(c: PContext, sym: PSym, info: TLineInfo,
   if sym != nil and sym.kind != skModule:
     for it in c.optionStack:
       let o = it.otherPragmas
-      if not o.isNil and sfFromGeneric notin sym.flags: # see issue #12985
+      if not o.isNil: # see issue #12985
```
Comment (ringabout) [inline compiler/pragmas.nim]:
```suggestion
      if not o.isNil:
```
