### ISSUE TITLE
C compiler error with sequtils.any with an iterator

### ISSUE THREAD

**Issue by ghost** [nim-lang/Nim#14273]
This code raises a C compiler error about an undeclared variable. FWIW compiles fine with `--gc:arc`. Reported by ``nisstyre`` on IRC (https://github.com/weskerfoot/Nimwin)

With Nim Playground I found that it worked in 0.19.6 and regressed in 0.20.0. Will try to bisect it

### Example
```nim
import sequtils

iterator getChildren(): string =
  let ignored = @['a']

  proc pred(x: char): bool = x.in(ignored)

  if any(@['a', 'b', 'c', 'd'], pred):
    yield "abcd"

for x in getChildren():
  echo x
# Calling the iterator twice is important here, otherwise it compiles
for x in getChildren():
  echo x
```

### Current Output
```
/home/dian/.cache/nim/nimwin_r/@mnimwin.nim.c: In function 'NimMainModule':
/home/dian/.cache/nim/nimwin_r/@mnimwin.nim.c:453:24: error: 'colonenv_' undeclared (first use in this function); did you mean 'colonenv__2'?
  453 |   genericSeqAssign((&(*colonenv_).ignored1), TM__EfTu0ppEE47Q9a0QdJI6b5g_4, (&NTI__lBgZ7a89beZGYPl8PiANMTA_));
```

### Expected Output
```
abcd
abcd
```

```
$ nim -v
Nim Compiler Version 1.3.1 [Linux: amd64]
Compiled at 2020-05-07
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 5fa7d374c4cb777372cf5b967575f228bda23c2b
active boot switches: -d:release
```

**Comment by ghost** [comment]
Now fails with arc too :)

**Comment by ghost** [comment]
Closing as a duplicate of https://github.com/nim-lang/Nim/issues/14165
