### PR TITLE
fix #19426 compile error using when/elif/else and typedesc in template

### LINKED ISSUE #19426: Regression: compile error using `when/elif/else`  and `typedesc` in template
Please help me find a better title for this issue.

The example compiles with 1.4.8 and returns error with 1.6.0.
Bisect has found 2aba116bbc8c1a595e49c8a703f2b8aecd7e8eda as first bad commit

Tested with both orc and refc

https://play.nim-lang.org/#ix=3MTf

### Example
```nim
type
  MyInt = object
    bitWidth: int

template toRealType*(t: MyInt): typedesc =
  when t.bitWidth == 32: int32
  elif t.bitWidth == 64: int64
  else: {.error.}

proc doFail(T: typedesc): T = default(T)

proc test =
  const myInt = MyInt(bitWidth:32)
  discard doFail(toRealType(myInt))

test()
```

### Current Output
```
Error: unhandled exception: field 'sym' is not accessible for type 'TNode' using 'kind = nkIdent' [FieldDefect]
```

### Expected Output
```
compilation successful
```

### Additional Information
It's a regression:

- 1.4.8: compiles successfully
- 1.6.0  up to devel: compilation error

### Bisect result
first bad commit: [2aba116bbc8c1a595e49c8a703f2b8aecd7e8eda] when statements branches exit early (#17143)

### PR DESCRIPTION
**Pull request by bung87**
fix #19426

### CODE REVIEW

File: compiler/semfold.nim [hunk 1]
```diff
@@ -460,18 +460,18 @@ proc foldFieldAccess(m: PSym, n: PNode; idgen: IdGenerator; g: ModuleGraph): PNo
   var x = getConstExpr(m, n[0], idgen, g)
   if x == nil or x.kind notin {nkObjConstr, nkPar, nkTupleConstr}: return
```
Comment (Araq) [inline compiler/semfold.nim:463]: Instead add a check

```nim
if n[1].kind != nkSym: return nil
```
