### ISSUE TITLE
Codegen error with threadvars 

### ISSUE THREAD

**Issue by dom96** [nim-lang/Nim#8211]
```nim
import times

var date {.threadvar.}: DateTime
proc update =
  date = now().utc()

proc foo() =
  echo(date.format("ddd, dd MMM yyyy HH:mm:ss 'GMT'"))

update()
foo()
```

```
Error: execution of an external compiler program 'clang -c  -w -pthread  -I/Users/dom/projects/nim/lib -o /private/tmp/aporia/nimcache/a4.o /private/tmp/aporia/nimcache/a4.c' failed with exit code: 1

/private/tmp/aporia/nimcache/a4.c:460:2: error: use of undeclared identifier 'date_IdIEGfJMJ2Y1BAYBtSMEnA'
        date_IdIEGfJMJ2Y1BAYBtSMEnA.Sup.m_type = (&NTI_S7qec11z7km5Pal3UXrHmw_);
        ^
1 error generated.
```

Be sure to compile with ``--threads:on``.

**Comment by dom96** [comment]
Workaround: storing ``Time`` instead of ``DateTime`` in the threadvar.

**Comment by dom96** [comment]
Appears to be working in 0.17.2.

**Comment by Vindaar** [comment]
Just ran this on current devel (https://github.com/nim-lang/Nim/commit/50aa376e802d949f430eba64ecd9f6beb86f91df) and this seems to be fixed for me.
