### ISSUE TITLE
compiler error with inline async proc and pragma

### ISSUE THREAD

**Issue by niv** [nim-lang/Nim#13998]
try/except in a async inline proc results in compiler error.

Repro'ed on 1.2.0, 1.3.1 Linux and MacOS. On 1.0.4 this worked fine.

**Only manifests on the cpp backend, not the c backend.**

### Example
```nim
import asyncdispatch

type SubscriptionHandler[T] = proc(subject, replyTo: string, data: T): Future[bool] # True to terminate subscription.

proc subscribe*[T](prefix: seq[string], queuegroup: string, cb: SubscriptionHandler[T]) {.async.} =
  discard await cb("dummy", "data", "ok")

proc reg() {.async.} =
  await subscribe(@["a", "b", "*"], "") do (
    sub, rep, dat: string
  ) -> Future[bool] {.async.}: # REM
    try:
      doAssert(false)
    except AssertionError:
      echo "assert"

asyncCheck reg()
```

Remove the `{.async.}` marked with REM to make the code compile on 1.2.0, but then it won't run.

### Current Output
```
/Users/niv/.cache/nim/regression_d/@mregression.nim.cpp:888:12: error: cannot jump from this goto statement to its label
                        case 1: goto STATE1;
                                ^
/Users/niv/.cache/nim/regression_d/@mregression.nim.cpp:896:23: note: jump bypasses variable initialization
                        std::exception_ptr T4_ = nullptr;                       try {
                                           ^
```

### Expected Output
```
No compiler error!
```

### Additional Information

* It was working in version 1.0.4

```
$ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-04-03
Copyright (c) 2006-2020 by Andreas Rumpf

git hash: 7e83adff84be5d0c401a213eccb61e321a3fb1ff
active boot switches: -d:release
```

**Comment by ghost** [comment]
Works for me on latest devel with both GCC and Clang (on Linux) in debug/release/danger, also checked and it works on Nim playground (1.2). Maybe it's macOS-specific (or specific to Clang on macOS)?

**Comment by niv** [comment]
Apologies. I forgot to mention this is only with the `cpp` backend. The `c` backend works fine.

Unfortunately, my project depends on the cpp backend due to various external dependencies.

I verified this to still be present with #head (1.3.1) and the cpp backend in use.

**Comment by valashko** [comment]
I have encountered the same issue while migrating the project from 0.20.0 to 1.2.0. Here is a simplified version
```nim
import asyncdispatch

proc printAsync() {.async.} =
    try:
        echo "good"
    except:
        echo "oops"

asyncCheck printAsync()
```
And the error message
```
/Users/val/.cache/nim/issue13998_d/@missue13998.nim.cpp:489:12: error: cannot jump from this goto statement to its label
                        case 1: goto STATE1;
                                ^
/Users/val/.cache/nim/issue13998_d/@missue13998.nim.cpp:492:23: note: jump bypasses variable initialization
                        std::exception_ptr T4_ = nullptr;                       try {
                                           ^
```

Environment
```
❯ nim -v
Nim Compiler Version 1.2.0 [MacOSX: amd64]
Compiled at 2020-04-04
Copyright (c) 2006-2020 by Andreas Rumpf

active boot switches: -d:release -d:nimUseLinenoise
❯ clang++ -v
Apple clang version 11.0.3 (clang-1103.0.32.59)
Target: x86_64-apple-darwin19.4.0
Thread model: posix
InstalledDir: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin
```

**Comment by valashko** [comment]
Seems like the issue was introduced by #13695. See new implementation of `proc genTryCpp`.
