### ISSUE TITLE
Constant sequence can not be passed as iterator openArray parameter to countup()

### ISSUE THREAD

**Issue by drbixx** [nim-lang/Nim#24305]
### Description

```
iterator demo(a: openArray[int]): int =
  for k in countUp(a[0], 19):
    yield 23

for k in demo(@[17]):
  echo k
```

### Nim Version

Nim Compiler Version 2.2.0 [Linux: amd64]
Compiled at 2024-10-02
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 78983f1876726a49c69d65629ab433ea1310ece1
active boot switches: -d:release

### Current Output

```text
/home/clean/.cache/nim/bug20241014_d/@mbug20241014.nim.c: In function ‘NimMainModule’:
/home/clean/.cache/nim/bug20241014_d/@mbug20241014.nim.c:138:142: error: lvalue required as unary ‘&’ operand
  138 |                         nimlf_(46, "/home/clean/.choosenim/toolchains/nim-2.2.0/lib/system/iterators_1.nim");                   colontmp_ = (&((NI)17));
      |                                                                                                                                              ^
Error: execution of an external compiler program 'gcc -c  -w -fmax-errors=3 -pthread   -I/home/clean/.choosenim/toolchains/nim-2.2.0/lib -I/home/clean/project/bug20241014 -o /home/clean/.cache/nim/bug20241014_d/@mbug20241014.nim.c.o /home/clean/.cache/nim/bug20241014_d/@mbug20241014.nim.c' failed with exit code: 1
```

### Expected Output

```text
None. This should compile and not generate a gcc or clang error.
```

### Known Workarounds

Using `seq[int]` as parameter type instead of `openArray[int]` makes the example compile.

### Additional Information

The problem can not be reproduced using lower versions of nim than version 2.2.0, which includes version 2.0.10.
The current `devel` is also affected, which is

Nim Compiler Version 2.2.1 [Linux: amd64]
Compiled at 2024-10-14
Copyright (c) 2006-2024 by Andreas Rumpf

git hash: 07628b0dec43dd417b6b536eff1c0f0a5c539b6d
active boot switches: -d:release

**Comment by ringabout** [comment]
!nim c
```nim
iterator demo(a: openArray[int]): int =
  for k in countUp(a[0], 19):
    yield 23

for k in demo(@[17]):
  echo k
```

**Comment by metagn** [comment]
Locally bisected to https://github.com/nim-lang/Nim/commit/0d24f765461785e5648ee580e0a4158eb344ee97

**Comment by metagn** [comment]
Another case:

```nim
iterator demo(a: array[1, int]): int =
  for k in countUp(a[0], 19):
    yield 23

for k in demo([17]):
  echo k
```

Where in the compiler does `a[0]` get folded?

**Comment by Araq** [comment]
in semfold.nim or vm.nim
