### PR TITLE
Fixed compilation error

### PR DESCRIPTION
**Pull request by yglukhov**
Introduced by #5317. `regAddr` is not used. @rokups, need your comment, or later fixup.

### CODE REVIEW

**Comment by Araq** [comment]
What compilation error was introduced?
