### ISSUE TITLE
Undeclared identifier in generated C code

### ISSUE THREAD

**Issue by gnois** [nim-lang/Nim#1807]
```
import asyncdispatch, asyncfile, asyncnet

proc sendSlowly(sock: AsyncSocket, file: AsyncFile) =

 proc onSent(future: Future[void]) {.gcsafe.}

 proc onRead(future: Future[string]) {.gcsafe.} =
  if not future.failed():
   if len(future.read) > 0:
    var f = sock.send(future.read)
    f.callback = onSent

 proc onSent(future: Future[void]) = 
  if not future.failed():
   var f = read(file, 8)
   f.callback = onRead

 var f = read(file, 10)
 f.callback = onRead

```

Compile with Nim 0.10.2 gives:

```
d:\nimprj\samples\nimcache\a.c: In function 'onsent_201008':
d:\nimprj\samples\nimcache\a.c:427:44: error: 'HEX3Aenv_201190' undeclared (first use in this function)
   LOC7.ClPrc = onread_201013; LOC7.ClEnv = HEX3Aenv_201190;
                                            ^
d:\nimprj\samples\nimcache\a.c:427:44: note: each undeclared identifier is reported only once for each function it appea
rs in
Error: execution of an external program failed
```

Is there a way to work around this issue?

**Comment by Araq** [comment]
Don't use a forward declaration and it should work, I hope.

**Comment by gnois** [comment]
Without the forward declaration the compiler gives:
```
a.nim(11, 17) Error: undeclared identifier: 'onSent'
```

because onRead calls onSent and vice versa.

**Comment by Araq** [comment]
try to mark the forward declaration with .closure

**Comment by gnois** [comment]
Like this?
```
 proc onSent(future: Future[void]) {.closure, gcsafe.}
```
The error is the same.

**Comment by dom96** [comment]
Still fails with error:

```
Error: execution of an external compiler program 'clang -c  -w  -I/Users/dom/projects/nim/lib -o /Users/dom/temp_code/nimcache/foo.o /Users/dom/temp_code/nimcache/foo.c' failed with exit code: 256

/Users/dom/temp_code/nimcache/foo.c:462:16: error: assigning to 'void (*)(FutureHEX3Aobjecttype170284 *, void *)' from incompatible type 'TY195047'
                        LOC14.ClPrc = LOC13; LOC14.ClEnv = NIM_NIL;
                                    ^ ~~~~~
1 error generated.
```

**Comment by Araq** [comment]
Now compiles for me. Closing for now.
