### ISSUE TITLE
regression(1.0): codegen error with `locals`

### ISSUE THREAD

**Issue by timotheecour** [nim-lang/Nim#12682]
regression(1.0): codegen error with `locals`

### Example
reduced from a more complex case:
```nim
  template foo*(): untyped =
    var c1 = locals()
    1

  proc testAll()=
    doAssert foo() == 1
    let c2=locals()
  testAll()
```

nim c -r main.nim

### Current Output
```
/nimcache/@mt0787.nim.c:102:14: error: use of undeclared identifier 'c1X60gensym393408_'
        c2.Field0 = c1X60gensym393408_;
```

### Expected Output
no error

### Additional Information
* It was working in version 0.19.0
* bug is in recent devel f22d3c75aa68833ae1b01d747d0c71074ccef310; also in 1.0.0

**Comment by ringabout** [comment]
It works since Nim v1.4.0
