### ISSUE TITLE
Tuple converter regression

### ISSUE THREAD

**Issue by johnnovak** [nim-lang/Nim#24609]
### Description

The below code used to work on 2.0.8 and before (going back several years), but it fails with a compilation error on 2.2.0.

Not sure if this is intentional; seems like an accidental regression to me that breaks existing code.

```nim
import std/options

type
  Config* = object
    bits*: tuple[r, g, b, a: Option[int32]]

# works on 2.0.8
#
# results in error on 2.2.0
#   type mismatch: got 'int literal(8)' for '8' but expected 'Option[system.int32]'
#
converter toInt32Tuple*(t: tuple[r,g,b,a: int]): tuple[r,g,b,a: Option[int32]] =
  (some(t.r.int32), some(t.g.int32), some(t.b.int32), some(t.a.int32))

var cfg: Config
cfg.bits = (r: 8, g: 8, b: 8, a: 16)
```

### Nim Version

2.2.0

### Known Workarounds

Don't use converters :)

**Comment by metagn** [comment]
!nim

```nim
import std/options

type
  Config* = object
    bits*: tuple[r, g, b, a: Option[int32]]

# works on 2.0.8
#
# results in error on 2.2.0
#   type mismatch: got 'int literal(8)' for '8' but expected 'Option[system.int32]'
#
converter toInt32Tuple*(t: tuple[r,g,b,a: int]): tuple[r,g,b,a: Option[int32]] =
  (some(t.r.int32), some(t.g.int32), some(t.b.int32), some(t.a.int32))

var cfg: Config
cfg.bits = (r: 8, g: 8, b: 8, a: 16)
```

**Comment by metagn** [comment]
!nim c

```nim
import std/options

type
  Config* = object
    bits*: tuple[r, g, b, a: Option[int32]]

# works on 2.0.8
#
# results in error on 2.2.0
#   type mismatch: got 'int literal(8)' for '8' but expected 'Option[system.int32]'
#
converter toInt32Tuple*(t: tuple[r,g,b,a: int]): tuple[r,g,b,a: Option[int32]] =
  (some(t.r.int32), some(t.g.int32), some(t.b.int32), some(t.a.int32))

var cfg: Config
cfg.bits = (r: 8, g: 8, b: 8, a: 16)
```

**Comment by metagn** [comment]
The reason is that the compiler now tries to match each individual element of the tuple constructor to the individual elements of the expected tuple type which gives an error trying to convert `int` to `Option[int32]`. The solution might be to just ignore any errors from matching the individual elements.
